### ISSUE TITLE
[Feature Request] A way to inject theme/palette colours into component.ts

### ISSUE THREAD

**Issue by pjmagee** [angular/components#11315]
####  feature request:

A way to inject Angular Material theme into component.ts files

#### What is the expected behavior?

A way to extract primary, accent, warn or other material palette colours from inside typescript of a component, as apposed to just styling based on the scss.

#### What is the current behavior?

Currently there is no built in behaviour that supports this, other than a exported def of ThemePalette which is a string of 'primary' | 'accent' | 'warn' under './common-behaviours'.

Currenty, the only way to theme is using the mixin approach and custom styles using the $theme object however this cannot be applied directly to js libraries that render in canvas such as chart.js etc.

#### What is the use-case or motivation for changing an existing behavior?

Making third party libraries easier to use and consume when you need to style them based on the current material theme. Many third party js libraries such as chart.js allow you to set the colours in js and do not provide ways of adding custom classes to style things, as they render into a canvas.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I'm currently using the latest version of Angular and Material. (6.0.1) 👍 

#### Is there anything else we should know?

This is my workaround but not sure if its the best solution and maybe something built in could be more helpful?

```c#
@Component({
    selector: 'app-theme-emitter',
    template: `<div #primary class='primary'></div>
               <div #accent class='accent'></div>
               <div #warn class='warn'></div>`,
    styles: [':host { display: none; }']
})
export class ThemeEmitterComponent implements AfterViewInit {

    primaryColor: string;
    accentColor: string;
    warnColor: string;

    @ViewChild('primary') primaryElement: ElementRef;
    @ViewChild('accent') accentElement: ElementRef;
    @ViewChild('warn') warnElement: ElementRef;

    ngAfterViewInit() {
        this.primaryColor = getComputedStyle(this.primaryElement.nativeElement).color;
        this.accentColor = getComputedStyle(this.accentElement.nativeElement).color;
        this.warnColor = getComputedStyle(this.primaryElement.nativeElement).color;
    }
}
```

```css

@mixin theme-emitter($theme) {

    $primary: map-get($theme, primary);
    $accent: map-get($theme, accent);
    $warn: map-get($theme, warn);

    app-theme-emitter {
        .primary {
            color: mat-color($primary);
        }
        .accent {
            color: mat-color($accent);
        }
        .warn {
            color: mat-color($warn);
        }
    }
}

```

Then, inside a custom component that uses Chart.js I am able to do the following to then configure the colours of the chart background etc:

```
@ViewChild(ThemeEmitterComponent)  theme: ThemeEmitterComponent;

ngAfterViewInit() {
   ...
   this.chartConfig.data.datasets[0].borderColor = this.theme.primaryColor;
   ...   
}

```

Relevant stackoverflow question: https://stackoverflow.com/questions/47791591/how-to-use-angular-material-theme-color-in-typescript-javascript/50328629#50328629
