### ISSUE TITLE
Mat-Button and Mat-Chips do not respect $fontConfig SCSS variables

### ISSUE THREAD

**Issue by arciisine** [angular/components#14359]
#### Bug, feature request, or proposal:
In the SCSS variable `$fontConfig`, the `button` property specifies the `font-size`, and `line-height` values for the `mat-button` elements.  Additionally, the `body-2` property specifies the stylings which are used for the `mat-chip` elements.

#### What is the expected behavior?
When modifying the `font-size` and `line-height` for buttons/chips, the padding should be relative to these variables.

#### What is the current behavior?
The padding is fixed, and is not relative to the `font-size`.  It is configurable, but not through the theme or it's variables.

#### What are the steps to reproduce?
The stackblitz app, https://angular-e7zgff.stackblitz.io, shows the material.angular.io button documentation, with the button `font-size` set to 9px with a `line-height` of 10px.
<img width="459" alt="screen shot 2018-12-02 at 8 00 32 pm" src="https://user-images.githubusercontent.com/1264175/49347504-1345a680-f66d-11e8-980c-adb9b801cb25.png">

#### What is the use-case or motivation for changing an existing behavior?
I'm working on a Material theme generator (http://materialtheme.arcsine.org), and the button `font-size` is a configurable property.  I am currently working around this by overriding the padding/line-height behavior to achieve the desired state.

```scss
// Handle buttons appropriately, with respect to line-height
.mat-raised-button, .mat-stroked-button, .mat-flat-button {
  padding: 0 1.15em;
  margin: 0 .65em;
  min-width: 3em;
  line-height: 36.4px // Computed from selected line-height for the font.
}

.mat-standard-chip {
  padding: .5em .85em;
  min-height: 2.5em;
}
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All
