### ISSUE TITLE
mat-button-toggle styling issues

### ISSUE THREAD

**Issue by fad250** [angular/components#14721]
Bug 1: 
#### Issue
Applying custom style for checked button toggle gives an odd hover effect. 

eg.

```
.mat-button-toggle-checked{
  background-color: #2979FF;
  color: white;
} 
```
![button-toggle-bug](https://user-images.githubusercontent.com/15860769/50687540-41b3fa00-0ffc-11e9-8dd3-1bf5ab0bd332.gif)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ivjb9g

Bug 2: 

#### Issue

In legacy style, button elevation cannot be modified. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ivjb9g-tdqden

**Comment by wottpal** [comment]
Does anybody now a temporary fix?

**Comment by skobak** [comment]
> Does anybody know a temporary fix? :)

A bit ugly hack, but works 
```
::ng-deep .mat-button-toggle-appearance-standard:not(.mat-button-toggle-disabled):hover .mat-button-toggle-focus-overlay {
    opacity: 0 !important;
}
```

**Comment by blogcraft** [comment]
I find mat-button-toggle the worst component of Angular Material.

**Comment by tawani** [comment]
> I find mat-button-toggle the worst component of Angular Material.

It is as if they literally wanted to make it horrible.

**Comment by zzeneg** [comment]
For bug 1:
The problem is in `color: white`, you have to set it on `.mat-button-toggle-checked button` to avoid it. Unfortunately it works only with `::ng-deep`. https://stackblitz.com/edit/angular-ivjb9g-sse7ch
On the other hand such overrides should be a part of your custom material theme, so just put it in your theme.scss:
```scss
.mat-button-toggle {
    button {
        color: mat-color($hatch-primary);
    }
}
.mat-button-toggle-checked {
    background-color: mat-color($hatch-primary);

    button {
        color: #fff;
    }
}
```
