### ISSUE TITLE
Prefers-Color-Scheme Support

### ISSUE THREAD

**Issue by tgotwig** [angular/components#16905]
#### Feature Description

Would be very nice to have Prefers-Color-Scheme Support in Angular Components:
https://davidwalsh.name/prefers-color-scheme

Except mobile devices this has pretty good browser-support already:
https://caniuse.com/#search=prefers-color-scheme

#### Use Case

The user has dark or light mode in his operating system enabled and based on this the Angular components would look like accordingly.

**Comment by jelbourn** [comment]
For now, we consider this to be an application-level concern. In particular, we never want to load both light and dark theme CSS at the same time out-of-the-box. Using a media query requires both sets of styles to be present at the same time, so we leave it up to the application to do this. That would look something like

```scss
@import '~@angular/material/theming';

@include mat-core();

$light-primary: mat-palette($mat-indigo);
$light-accent:  mat-palette($mat-pink, A200, A100, A400);
$light-theme:   mat-light-theme($candy-app-primary, $candy-app-accent);

@media (prefers-color-scheme: light) {
  @include angular-material-theme($light-theme);
}


$dark-primary: mat-palette($mat-blue-grey);
$dark-accent:  mat-palette($mat-amber, A200, A100, A400);
$dark-warn:    mat-palette($mat-deep-orange);
$dark-theme:   mat-dark-theme($dark-primary, $dark-accent, $dark-warn);

@media (prefers-color-scheme: dark) {
  @include angular-material-theme($dark-theme);
}
```
