### ISSUE TITLE
Dense text fields

### ISSUE THREAD

**Issue by Toso82** [angular/components#17588]
#### Feature Description

Possibility to add Dence text field as Material Spect

https://material.io/components/text-fields/#outlined-text-field

#### Use Case

Actualy use this when there is not label 

```css
.mat-form-field:not(.mat-form-field-has-label) .mat-form-field-infix {
  border-top-width: 0;
}
```
