### ISSUE TITLE
mat-card-title takes font weight from headline, weight from title and lineheigt from body

### ISSUE THREAD

**Issue by fabianpage** [angular/components#17599]
I'm not sure if that is a bug or if it is by design but i would expect mat-card-title to use size, weight and line-heigt from only one style not a mixture of 3 styles:

I would expect
https://github.com/angular/components/blob/master/src/material/card/_card-theme.scss#L32
to be more like that:
```scss
  .mat-card-title {
    font: {
      size: mat-font-size($config, title);
      weight: mat-font-weight($config, title);
    }
    line-height: mat-line-height($config, title);
  }
```
