### ISSUE TITLE
theme/color: Add selector class names for the current mat colors. (like "mat-app-background") 

### ISSUE THREAD

**Issue by Domvel** [angular/components#18722]
#### Feature Description

I would be great if Angular Material implements class-names for the active theme colors.

There is already a class `mat-app-background` to get the background color. Very helpful if you use the dark theme. https://material.angular.io/guide/theming (search for "mat-app-background")

Theming is a challenging job for non-mat elements like `div`. I found a solution for me (see below). But Angular Material should simplify this by build in these features. `mat-app-background` already exists - why not for colors too?

Ok, there are two cases for styling:

- Background and text contrast. (use class-name e.g. `mat-color-primary`)
- Text only with the background color. (use class-name e.g. `mat-color-primary-text`)

#### Use Case

Style every element by simply adding the color class name into the html element. No hassle. No own / custom implementation.

#### My Current Solution

This is the complete file for light and dark theme. Simply add `dark-theme` class to the body. 
NOTE: Also add the class `mat-app-background` to the `body` element. (or a level deeper.)

```scss
@import "~@angular/material/theming";

@include mat-core();

// LIGHT
$custom-app-light-primary: mat-palette($my-blue);
$custom-app-light-accent: mat-palette($my-green);
$custom-app-light-warn: mat-palette($mat-red);

$custom-app-light-theme: mat-light-theme(
  $custom-app-light-primary,
  $custom-app-light-accent,
  $custom-app-light-warn
);
@include angular-material-theme($custom-app-light-theme);

// DARK
$custom-app-dark-primary: mat-palette($my-blue);
$custom-app-dark-accent: mat-palette($my-green-light);
$custom-app-dark-warn: mat-palette($mat-red);

$custom-app-dark-theme: mat-dark-theme(
  $custom-app-dark-primary,
  $custom-app-dark-accent,
  $custom-app-dark-warn
);

.color-primary {
  background-color: mat-color($custom-app-light-primary);
  color: mat-color($custom-app-light-primary, default-contrast);
}

.color-accent {
  background-color: mat-color($custom-app-light-accent);
  color: mat-color($custom-app-light-accent, default-contrast);
}

.color-warn {
  background-color: mat-color($custom-app-light-warn);
  color: mat-color($custom-app-light-warn, default-contrast);
}

.dark-theme {
  @include angular-material-theme($custom-app-dark-theme);

  .color-primary {
    background-color: mat-color($custom-app-dark-primary);
    color: mat-color($custom-app-dark-primary, default-contrast);
  }

  .color-accent {
    background-color: mat-color($custom-app-dark-accent);
    color: mat-color($custom-app-dark-accent, default-contrast);
  }

  .color-warn {
    background-color: mat-color($custom-app-dark-warn);
    color: mat-color($custom-app-dark-warn, default-contrast);
  }
}
```

Btw. my proposal with the text color is about creating class names with `-text` suffix. Like: 

```scss
.color-primary-text {
  color: mat-color($custom-app-dark-warn);
}
```

So with my solution you have solved the color styling for both cases. Backgroud with contrast for text color and text color only.

```html
<div class="color-primary">Awesome!</div>
<!-- Or with your official way (naming):-->
<div class="mat-color-primary">Awesome!</div>
```
