### ISSUE TITLE
MatDatepicker: MatDatepickerParse shows blank error if the field is empty

### ISSUE THREAD

**Issue by laneschmidt** [angular/components#19331]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

https://stackblitz.com/edit/components-issue-nkebqj?file=src%2Fapp%2Fexample-component.ts

Steps to reproduce:
1. Hit submit with a blank datepicker
 
I can't reproduce in the Stackblitz.
 
#### Expected Behavior

What behavior were you expecting to see?
The MatDatepicker should allow for an empty field.

#### Actual Behavior

What behavior did you actually see?
The MatDatepicker adds an error to the FormControl's errors array, with MatDatepickerParse. The error text is `""`. 

From the form:
```
date: FormControl
  asyncValidator: null
  errors:
    matDatepickerParse:
      text: ""
  __proto__: Object
  __proto__: Object
  pristine: true
  status: "INVALID"
```

#### Environment

- Angular: 9.0.4
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS
