### ISSUE TITLE
bug(Material Input): Material Elements going out of div

### ISSUE THREAD

**Issue by wh0th3h3llam1** [angular/components#19791]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48444630/85625683-7781ee00-b689-11ea-9993-902c26e2c52c.gif)
 
#### Expected Behavior

What behavior were you expecting to see?
The Floating label should be within the div and should be visible (for input with and without outline);
Slide Toggle should be fully visible
For Badges on mat-icons, they are only partly visible

#### Actual Behavior

What behavior did you actually see?
The floating label is hiding behind div, 
Slide Toggle is only partly visible,
For Badges on mat-icons, they are only half visible

#### Environment

- Angular: 9.2.3
- CDK/Material: 9.2.3
- Browser(s): FireFox, FireFox Developer Edition, Microsoft Edge, Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10, Ubuntu

**Comment by crisbeto** [comment]
From what I can tell there are some styles in your app that are overriding the Material styles and causing them to be clipped.

**Comment by wh0th3h3llam1** [comment]
I think it started happening after I installed @angular/flex-layout module. 
Any solutions?

**Comment by wh0th3h3llam1** [comment]
My styles.css

```css
/* You can add global styles to this file, and also import other style files */
*
{
	overflow-x: hidden;
}

html, body { height: 100%; }
body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
```

app.component.css

```css
.header
{
	text-align: center;
	font-size: x-large;
}

.center
{
	text-align: center;
	justify-content: center;
	align-items: center;
}

.form-input
{
	width: 400px;
}

.container
{
	padding: 30px;
}

mat-card
{
	width: 500px;
}

mat-slide-toggle
{
	height: 30px;
}
```
