### ISSUE TITLE
bug(expansion-panel): description not aligned when mixing rows with and without toggle

### ISSUE THREAD

**Issue by macjohnny** [angular/components#20002]
#### Reproduction

Open example "Basic expansion panel": 
https://material.angular.io/components/expansion/examples

 
 
#### Expected Behavior

The descriptions should be horizontally aligned.

#### Actual Behavior

The descriptions are not aligned

![expansion-panel](https://user-images.githubusercontent.com/5589029/87646361-0b0d8280-c74f-11ea-8f4b-6dbc735c219b.png)

#### Environment

- Angular: 10
- CDK/Material: 10.0.2
- Browser(s): Chrome
- Operating System: Windows

**Comment by swseverance** [comment]
@macjohnny I don't think a PR to fix this is going to be merged any time soon. In the meantime, if you want to fix this with css I would recommend the following:

```css
.mat-content:only-child {
  margin-right: 8px;
}

.mat-expansion-panel-header-title,
.mat-expansion-panel-header-description {
  flex-basis: 0;
}
```

[StackBlitz](https://stackblitz.com/edit/angular-odu69m)
