### ISSUE TITLE
bug(toolbar): the CSS regarding the height of the toolbar is not included anymore 

### ISSUE THREAD

**Issue by ahasall** [angular/components#20108]
I think there is an undocumented breaking change in the toolbar component.

I’ve updated an Angular Material application from v9 to v10 and saw that the height of the toolbar is broken.
I’ve gone through the CHANGELOG, but I didn’t find anything related to that. I’ve done a diff between v9 and v10 prebuilt themes CSS files and saw a chunk of CSS removed.

#### Reproduction

For reproduction, compare the prebuilt themes for v9 and v10:
* [indigo-pink v9](https://unpkg.com/@angular/material@9.2.4/prebuilt-themes/indigo-pink.css)
[indigo-pink 1v0](https://unpkg.com/@angular/material@10.0.1/prebuilt-themes/indigo-pink.css) 

 
 
#### Expected Behavior

The CSS generated for the toolbar in Angular Material v9 included the following code:
```css
.mat-toolbar-multiple-rows {
    min-height: 64px
}

.mat-toolbar-row, .mat-toolbar-single-row {
    height: 64px
}

@media (max-width: 599px) {
    .mat-toolbar-multiple-rows {
        min-height: 56px
    }

    .mat-toolbar-row, .mat-toolbar-single-row {
        height: 56px
    }
}
```

#### Actual Behavior

In v10, this chunk of CSS disappeared.

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): All browsers
- Operating System (e.g. Windows, macOS, Ubuntu): All operating systems
