### ISSUE TITLE
cdkDrag: with cdkDropList -> wrong Cursor when dragging

### ISSUE THREAD

**Issue by Flo0806** [angular/components#20246]
Hi all,
![issue_1](https://user-images.githubusercontent.com/10813063/88395832-f91c8700-cdc1-11ea-9184-9188f1340b8c.png)
![issue_2](https://user-images.githubusercontent.com/10813063/88395836-f9b51d80-cdc1-11ea-8e1f-794c089706d6.png)

**Here is a little sample.**
[https://stackblitz.com/angular/yvmnrxexppp?file=app%2Fcdk-drag-drop-connected-sorting-example.html](url)

Since version 7.2.x (I noticed) there is the problem that the cursor (set in CSS) adapts to the underlying object during the dragging process.

If the cursor is changed to "move" and I use e.g. move an "input" (drag) then the cursor changes from move to input.

This phenomenon only occurs with cdkDropList, not when the cdkDrag property is only set for a single object.

The CSS:
```css
.example-box {
  padding: 20px 10px;
  border-bottom: solid 1px #ccc;
  color: rgba(0, 0, 0, 0.87);

  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
  box-sizing: border-box;
  cursor: move;
  background: white;
  font-size: 14px;
}
```

The HTML:
```html
   <div class="col-md-4">

      <div class="drag-container">
        <div class="section-heading">Still Doing</div>
        <div cdkDropList #pendingList="cdkDropList" [cdkDropListData]="todo"
          [cdkDropListConnectedTo]="[doneList,reviewList]" class="item-list" (cdkDropListDropped)="drop($event)">
          <div class="item-box" *ngFor="let item of todo" cdkDrag>{{item}}</div>
        </div>
      </div>
    </div>
```
