### ISSUE TITLE
Docs titles are clipped on the left side

### ISSUE THREAD

**Issue by zbralex** [angular/components#20687]
#### please, fix css margin property at anchors titles

```scss
.docs-header-link header-link a {
text-decoration: none;
 /* margin-left: -30px; */ this property hide anchors at the page titles
 display: inline-block;
vertical-align: middle;
}
```

If margin value -30px I can't see anchor for navigate
https://material.angular.io/components/table/overview#filtering

**Affected documentation page:** https://material.angular.io/components/table/overview
