### ISSUE TITLE
feat(Table): detect clickable mat-rows with routerLink

### ISSUE THREAD

**Issue by alvaromartmart** [angular/components#20752]
#### Feature Description
Material table rows are not displayed as clickable elements (i.e. hover effect, cursor: pointer...) when they have an attached `routerLink` directive.

Things I've tried:
```html
<tr
    mat-row
    *matRowDef="let rowData; columns: visibleColumns$ | async"
    [routerLink]="[id]">
</tr>
``` 
Hovering the rows doesn't indicate that the row is clickable.

Solutions I've been using:
1) Setting a fake (click) handler for the row:
```html
<tr
    mat-row
    *matRowDef="let rowData; columns: visibleColumns$ | async"
    [routerLink]="[id]"
    (click)="(false)">
</tr>
``` 
2) Styling .mat-rows with attached routerLink (using ng-reflect-router-link)
```scss
.mat-row[ng-reflect-router-link]{
    cursor: pointer;
    &:hover{
        /* [...] */
    }
}
```

#### Use Case

From my point of view, material table rows with routerLinks should be displayed as clickable elements.
