### ISSUE TITLE
bug(dialog): dialog's content text color is not secondary-text

### ISSUE THREAD

**Issue by c-kunz** [angular/components#20973]
#### Description

When looking at the Material Design page of Dialogs (https://material.io/components/dialogs#anatomy) one can see that the Dialog's content text (in the Anatomy example this is labeled as *Supporting text*) is displayed in a lighter gray than the title.

#### Reproduction

Repository: https://github.com/c-kunz/mat-dialog-content-secondary-text

Steps to reproduce:
1. `git clone https://github.com/c-kunz/mat-dialog-content-secondary-text repro`
2. `cd repro`
3. `npm i`
4. `ng serve -o`
 
#### Expected Behavior

I would expect the dialog's content to be in a lighter gray than the title. When looking at the Angular Material Theme Color Configuration I would expect this to be:

`theme-or-color-config: foreground: secondary-text`.

#### Actual Behavior

The dialog's content text color is the same as the title's color (`rgba(0,0,0, 0.87)`).

#### Workaround attempt

I've tried to find a fitting CSS class as described in here, but with no luck: https://material.angular.io/guide/typography#material-typography-in-your-custom-css

I've tried to do the following:

```scss
$theme: ...
.my-theme {
    @include angular-material-theme($theme);

    .mat-dialog-content {
        color: map-get(map-get($theme, foreground), secondary-text);
    }
}
```

But this causes every text to be displayed in that `secondary-text`, even in `mat-form-fields` where I want the darker variant so it can be read better.

#### Environment

- Angular: 10.2.2
- CDK/Material: 10.2.7
