### ISSUE TITLE
feat(mat-form-field): add CSS class about the contained mat-hint

### ISSUE THREAD

**Issue by smnbbrv** [angular/components#21664]
#### Feature Description

Please add a special class to mat-form-field indicating that mat-hint is inside (and for mat-error for convenience?).

#### Use Case

Hi Angular team,

I'm trying to implement specific CSS logic for the `mat-form-field` and its margin on the bottom that the form fields have the same spacing between them. Yes, in this case the jumping behaviour on the error / hint toggle is the sacrifice.

However implementing is not that simple. Here is what I have so far:

```css
.mat-form-field-wrapper {
  margin-bottom: -1.4em;

  .mat-paginator &,
  .mat-form-field-invalid & {
    margin-bottom: 0;
  }
}
```

This covers the errors and the information about the errors is already available via `.mat-form-field-invalid` class.

And here is what is desired

```css
.mat-form-field-wrapper {
  margin-bottom: -1.4em;

  .mat-paginator &,
  .mat-form-field-invalid &,
  .mat-hint-inside & {
    margin-bottom: 0;
  }
}
```

Currently I work this around with following directive:

```ts
import { Directive, OnDestroy, OnInit } from '@angular/core';
import { MatFormField } from '@angular/material/form-field';

@Directive({
  selector: '[matHint]', // tslint:disable-line
})
export class MatHintDirective implements OnInit, OnDestroy {

  constructor(
    private matFormField: MatFormField,
  ) {
  }

  ngOnInit() {
    this.formFieldElement.classList.add('mat-hint-inside');
  }

  ngOnDestroy() {
    this.formFieldElement.classList.remove('mat-hint-inside');
  }

  private get formFieldElement() {
    return this.matFormField._elementRef.nativeElement as HTMLElement;
  }

}
```

This is ugly and not that functionable, but that's the simplest way I found so far.
