### ISSUE TITLE
bug(mdc-progress-bar): Does not flip with body set to `dir="rtl"`

### ISSUE THREAD

**Issue by andrewseguin** [angular/components#22609]
The legacy progress bar has specific styles to flip its directionality based on a parent having `[dir='rtl']`:

```scss
  // Reverse the apparent directionality of progress vars for rtl.
  &[dir='rtl'],
  [dir='rtl'] & {
    transform: rotateY(180deg);
  }

  &[mode='query'] {
    transform: rotateZ(180deg);

    &[dir='rtl'],
    [dir='rtl'] & {
      transform: rotateZ(180deg) rotateY(180deg);
    }
  }
```

However, this is missing from the new MDC-based progress bar. Should this extra code be included? An internal test fails due to this case, but perhaps it should have been implemented otherwise through the Directionality service?
