### ISSUE TITLE
feat(Elevation class helpers): Expose transition-property-value

### ISSUE THREAD

**Issue by MuMaestro** [angular/components#22699]
#### Feature Description

While building styles for elements that use transitions of elevations and other values, the elevation-transition get overridden or overwrites other transitions defined in the same component. This could be easily solved by exposing the private-transition-property-value that returns a value inserted in a transition;

#### Use Case

By exposing the function, it could be used as as follows
```scss
.element {
     transition: border 1s ease-in, transition-property-value(), width 1s ease-in;
}
```

### Also

I don't know much css or scss, but I guess there is a hacky way of inheriting already set transitions, appending to the current list.
