### ISSUE TITLE
MDC button density is overridden by base button styles

### ISSUE THREAD

**Issue by jelbourn** [angular/components#22728]
The MDC button's `button.scss` file emits the following style:
```css
.mdc-button {
  height: 36px;
  border-radius: 4px;
  border-radius: var(--mdc-shape-small, 4px);
  padding: 0 8px 0 8px
}
```

When applying button density via theme mixin, the correct `height` is emitted into the theme (density -2 here):
```css
.mat-mdc-button, 
.mat-mdc-raised-button, 
.mat-mdc-unelevated-button, 
.mat-mdc-outlined-button {
  height: 28px;
  margin-top: 0;
  margin-bottom: 0
}
```

In the vast majority of cases, people will include their theme file in the document head. Angular, however, will append component-specific styles at the _end_ of the head, meaning that the button's base styles will take precedence over the theme style.
