### ISSUE TITLE
bug(material-experimental): mdc-tab does not respect foreground color in dark mode

### ISSUE THREAD

**Issue by AmitMY** [angular/components#23269]
#### Reproduction

Steps to reproduce:
1. Use `mat-tab-group` in the `material-experimental` package
2. Change your computer theme to dark mode
 
 
#### Expected Behavior

In dark mode, the tab text should be the foreground text (white).
```scss
.mdc-tab
    @media (prefers-color-scheme: dark) {
      color: map-get($mat-dark-theme-foreground, text);
    }
}
```

#### Actual Behavior

Tab text is black, like in light mode

#### Environment

- Angular: 12.1.3
- CDK/Material: Experimental, 12.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
