### ISSUE TITLE
bug(MDC_FORM_FIELD): TITLE

### ISSUE THREAD

**Issue by kaspnilsson** [angular/components#23509]
## Observed behavior: 
Outlined input's floating label does not comply with custom typography -- only applies to MDC component.

In addition, MDC component does _not_ shrink in height the same way the non-MDC component does -- not sure why this would be

To actually reproduce this, you unfortunately need to create two separate modules and export two separate components so the `[matInput]` directives don't collide, but this is the gist of the repro case:

Code:
```html
<div class="non-mdc">
  <mat-form-field appearance="outline">
    <mat-label>Non-MDC label</mat-label>
    <input matInput placeholder="A placeholder"  />
  </mat-form-field>
</div>
<div class="mdc">
  <mat-form-field appearance="outline">
    <mat-label>MDC label</mat-label>
    <input matInput placeholder="A placeholder"  />
  </mat-form-field>
</div>
```
```scss
.non-mdc {
  @include mat.form-field-theme($app-theme); // some init theme
}

$small-typography: mat.define-typography-level(12px, 16px, 400, $roboto-font, 0.3px);

$form-field-typography: mat.define-typography-config(
  $body-2: $small-typography,
  $subheading-1: $small-typography,
  $input: $small-typography,
);

.mdc {
  @include mat.mdc-form-field-theme($app-theme); // some init theme
  @include mat.mdc-form-field-typography($form-field-typography);
}

.mdc,
.non-mdc {
  font-size: 12px;
}
```
## Screen recording: 

https://user-images.githubusercontent.com/5749398/131729202-5c30d0b1-8a58-4b43-95ae-adc931757455.mp4

## Expected behavior: 

- Floating label is _definitely_ wrong
- Feature parity with upgrade re: input height auto-resizing may be desirable, not sure. May also be related to the first problem somehow
