### ISSUE TITLE
help(google-maps): How to set width and height to 100% of parent?

### ISSUE THREAD

**Issue by vladkasianenko** [angular/components#24088]
### What are you trying to do?

I'm trying to set width of maps to 100%.

``` html
<div class="container">
   <google-maps [options]="options"></google-maps>
</div>
```
```css
.container {
   width: 100%;
   height: 100%;
}
```

![image](https://user-images.githubusercontent.com/14053728/145690833-ec165d7d-9e59-450b-9e3b-891c650c4d64.png)
Map should fill the red block.

### What troubleshooting steps have you tried?

I tried to use:
``` html
<div class="container">
   <google-maps height="100%" width="100%" [options]="options"></google-maps>
</div>
```
and
```css
:ng-deep .map-container {
   width: 100% !important;
   height: 100% !important;
}
```

However this is working sometimes, but looks weird and unreliable,
``` html
<div class="container" #mapContainer>
   <google-maps [width]="mapContainer.offsetWidth" [height]="mapContainer.offsetHeight" [options]="options"></googleMaps>
</div>
```
![image](https://user-images.githubusercontent.com/14053728/145691262-3ae02482-8d7b-41c4-ae76-4f551aa03eff.png)

with no luck.

Leaving everything without `height` and `width` makes the default `500px`.

### Reproduction

Just install.

### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): Edge Chromium
- Operating System: Windows
