### ISSUE TITLE
help(Upgrade): Unable to finish upgrade from 12 to 13 due to scss issues

### ISSUE THREAD

**Issue by HarelM** [angular/components#24227]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12

### Description

When upgrading from angular 12 to angular 13 of the material library the upgrade completes successfully but the build fails with cryptic error message.

### Reproduction

Steps to reproduce:
1. clone https://github.com/IsraelHikingMap/Site
2. cd IsraelHiking.Web
3. upgrade angular from 12 to 13
4. upgrade material from 12 to 13
5. run npm run build:watch
6. Build fails with the following error message:
```
SassError: expected "{".
  ╷
1 │ @use "@angular/material" as mat;
  │                                  ^
  ╵
  src/scss/sidebar.scss 1:34  @import
  src/scss/common.scss 6:9    root stylesheet
```

### Expected Behavior

Upgrade should complete successfully and build should pass.

### Actual Behavior

Unable to use material 13 due to this cryptic error which I haven't found a way to workaround or fix.

### Environment

- Angular: 13
- CDK/Material: 13
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): maxOS

**Comment by HarelM** [comment]
I've pushed the upgrade I did besides material 12->13 to the following branch.
Feel free to try and upgrade only material and then build to see the error:
https://github.com/IsraelHikingMap/Site/tree/maplibre2

**Comment by crisbeto** [comment]
Based on the stack trace, I'm guessing that you're either running an old version of Sass that doesn't support `@use` or you're running `node-sass` which is unsupported.

**Comment by HarelM** [comment]
I already am using `@use` in my project, the upgrade changed from using `~@angular...` to `@angular`.
I might be using an old version of Sass, but shouldn't the upgrade take care of this?
I'm using angular for a long time (since version 2 I think with this project) and I try my best to upgrade only using the supplied tools.
If there's something I should be doing differently I'd love to know :-)

**Comment by crisbeto** [comment]
The tilde before imports has been deprecated in the CSS Webpack loader for a long time. We removed it automatically in v13, because it would've conflicted with the new Angular package format as well. You can try this as well https://github.com/angular/components/issues/23961#issuecomment-981098409

**Comment by HarelM** [comment]
Thanks @crisbeto ! I'll try it although I don't have high expectations...
I'm mainly concerned about the following file which I'm not sure how to migrate so that it will be valid in angular 13:
```scss
@use "~@angular/material" as mat;
@import "../fonts/icons.css";
@import "font-awesome/css/font-awesome.css";
@import "~maplibre-gl/dist/maplibre-gl.css";
@import "./dialogs.scss";
@import "./sidebar.scss";
@import "./_variables.scss";

@include mat.core();
@include mat.all-component-themes($app-theme);

html {
    height: 100%;
}
...
```
Can be found here:
https://github.com/IsraelHikingMap/Site/blob/main/IsraelHiking.Web/src/scss/common.scss
