### ISSUE TITLE
bug(VirtualScroll): Horizontal scrolling inside cdk-virtual-scroll-viewport

### ISSUE THREAD

**Issue by Spinnenzunge** [angular/components#24277]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Content inside the cdk-virtual-scroll-viewport does use more than 100% width and does not break anymore and instead adds horizontal scrolling.

This is especially a problem when using following css rules:

```
white-space: nowrap;
overflow: hidden;
```

The problem is the created wrapper container with the `cdk-virtual-scroll-content-wrapper` class that has a `min-width: 100%` set but no `max-width` and can not be changed because of the view encapsulation.

### Reproduction

https://github.com/DaniLopes2003/VirtualScroll-DemoApp

### Expected Behavior

No horizontal scroll bar added or width, max-width and min-width customizable with css variables?

### Actual Behavior

Horizontal bar added because no min-width is set

### Environment

- Angular: 13.0.3
- CDK/Material: 13.1.3
- Browser(s): Chrome, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by wagnermaciel** [comment]
@mmalerba Could you take a look

**Comment by saladfingerss** [comment]
I'm also having this problem so am keen on a fix too, thanks all

**Comment by rdlabo** [comment]
In my environment, this css fixed this issue:

```css
cdk-virtual-scroll-viewport {
  height: 100%;
  width: 100%;

  .cdk-virtual-scroll-content-wrapper {
    max-width: 100% !important;
  }
}
```

**Comment by saladfingerss** [comment]
This worked for me, thanks @rdlabo

**Comment by john-legallynoticed** [comment]
Can confirm this fix works, and that this is still an issue in Angular CDK 15. Fought this bug for hours before I found this thread. This is a pretty significant issue when creating complex layouts with clipped wrapping on mobile devices. Without this fix nothing you do can limit the width of a child component within the virtual scroller if you have white-space:nowrap set. Ironically this issue makes it much more difficult to guarantee a fixed height for the scrolled items.

**Comment by andersonjohnf** [comment]
Can confirm this fix works, and that this is still an issue in Angular CDK 15. While the fix is simple finding the issue is not. If this is intended functionality it could at the very least be mentioned in the docs, along with this option if a fixed 100% width is desired.

**Comment by mchlroy** [comment]
Workaround does not work as is for me because of the encapsulation (as mentioned in the issue description). I would have to use ng-deep. 

```css
cdk-virtual-scroll-viewport {
    height: 100%;
    width: 100%;

    ::ng-deep .cdk-virtual-scroll-content-wrapper {
        max-width: 100% !important;
    }
}
```

Which I'd prefer not to since it is not recommended.
