### ISSUE TITLE
feat(MatSelect): Optional header component in the overlay panel

### ISSUE THREAD

**Issue by rhilliges** [angular/components#24289]
### Feature Description

Add the option to add a custom component as a header in the overlay panel (kind of like in the date-picker).

### Use Case

When a select field has a lot of items, it would be nice to show the user a search input field on top of the list in order to filter the items.

**Comment by lekhmanrus** [comment]
You can currently add a custom `MatSelect` header.
```html
  <mat-select>
    <div class="some-header">Some header</div>
    <mat-option *ngFor="let food of foods" [value]="food.value">
      {{food.viewValue}}
    </mat-option>
  </mat-select>
```

```scss
    .some-header {
      background-color: #0ea5e9;
      border-bottom: 3px solid #0284c7;
      color: #fff;
      font-size: 1.25rem;
      padding: 15px;
      text-align: center;
    }
```
