### ISSUE TITLE
bug(mat-select-trigger): error at labels

### ISSUE THREAD

**Issue by xprojects-de** [angular/components#24747]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

Updating Material to 13.3.* the mat-trigger-lables are not working anymore (see screenshots).
Reason for that is that the class "mat-select-trigger" uses table-cell before and no flex is used.

```css
.mat-select-trigger {
  display: inline-flex;
  align-items: center;
  cursor: pointer;
  position: relative;
  box-sizing: border-box;
  width: 100%;
}

.mat-select-trigger {
  display: inline-table;
  cursor: pointer;
  position: relative;
  box-sizing: border-box;
}

```

![Bildschirmfoto 2022-04-07 um 08 51 27](https://user-images.githubusercontent.com/55982921/162140260-f1104e58-3b80-4c12-9689-16c6be8f7e9b.png)
![Bildschirmfoto 2022-04-07 um 08 51 36](https://user-images.githubusercontent.com/55982921/162140265-d3b569ff-fa28-46a4-8360-2a6658e53181.png)

### Reproduction

creating a multi-select with mat-chips as mat-trigger labels

### Expected Behavior

shoudl work like before

### Actual Behavior

see screenshot. Labels are out of bound!

### Environment

- Angular: 13.3.2
- CDK/Material: 13.3.2
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all
