### ISSUE TITLE
bug(mat-tabs): MatMenu within a MatTabNavPanel causes ChangedAfterChecked errors

### ISSUE THREAD

**Issue by JaimeStill** [angular/components#24939]
### Feature Description

> Submitting as a Feature as I'm pretty sure the below scenario isn't officially supported by MDL.

[StackBlitz Scenario](https://stackblitz.com/edit/tab-embedded-menu)

When building out child routes accessed via a `<nav mat-tab-nav-bar>`, it's helpful to provide a button or menu exposing common functionality directly within the tab panel (vs. adding another panel parallel or adjacent to the tab panel). This technically works by linking a `mat-tab-link` to a menu, but it triggers the following console errors when the menu is opened / closed:

![image](https://user-images.githubusercontent.com/14102723/169138122-38153fea-68a0-4339-9abf-728b2693c6e1.png)

If I change the menu trigger to a simple `<a mat-button>`, the styling for the button does not conform to the styling of the tabs in the nav panel:

![image](https://user-images.githubusercontent.com/14102723/169138416-fdefea31-99b9-4e15-8b1d-edf271159643.png)

Recommendation would be to adjust styling for `mat-button` to to conform to tab styling when embedded in a `mat-tab-nav-bar`:

```scss
nav.mat-tab-nav-bar .mat-button {
  height: 48px;
  padding: 0 24px;
  opacity: .6;
  text-align: center;
  display: inline-flex;
  justify-content: center;
  align-items: center;
  white-space: nowrap;
  vertical-align: top;
  text-decoration: none;
  position: relative;
  overflow: hidden;
}
```

![image](https://user-images.githubusercontent.com/14102723/169138952-2b87435b-d10a-4875-8e2d-e72767cb0421.png)
