### ISSUE TITLE
bug(material/tabs): ink bar animation not disabling when animationDuration set to 0

### ISSUE THREAD

**Issue by midgleyc** [angular/components#25068]
### Feature Description

I can set the animation duration for the tabs themselves using `animationDuration` on the `mat-tab-group`. If I set this to 0, the tabs switch instantly, but the ink bar moves across taking 500ms, which makes the tab switching look slower than it actually is.

I can implement this myself using `ng-deep`:

```css
::ng-deep .mat-ink-bar {                                                                             
  transition: none !important;                                                                       
}
```

but `ng-deep` is deprecated, so there's always the risk this will stop working in the future.

### Use Case

Tab switching looks faster if tab switch animation duration is less than 500ms.
