### ISSUE TITLE
bug(button): Palette contrast values are not applied

### ISSUE THREAD

**Issue by mlimones-pensare** [angular/components#26056]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.x

### Description

When using a custom theme the contrast values from a custom palette are not applied

### Reproduction

# steps
- define a custom palette with a "slightly light" color and a white contrast color

``` css
$md-secondary: (
  ...
  500 : #f86072,
  ...
contrast: (
  ...
    500 : #ffffff
  ...
  )
);
```
- Apply the theme
```css
$theme-primary: mat.define-palette($md-primary,500);
$theme-accent: mat.define-palette($md-secondary,500);
$theme-warn: mat.define-palette(mat.$red-palette);
$theme: mat.define-light-theme((
  color: (
    primary: $theme-primary,
    accent: $theme-accent,
    warn: $theme-warn,
  ),
  typography: mat.define-typography-config(),
));
@include mat.all-component-themes($theme);
```
# example: 

https://stackblitz.com/edit/angular-5b8rw5?file=src/theme.scss

### Expected Behavior

Text in accent button should be white (contrast color) as specified in the palette

### Actual Behavior

Text in accent button is black

### Environment

- Angular:15.0.0
- CDK/Material:15.0.0
- Browser(s):chrome, safari
- Operating System (e.g. Windows, macOS, Ubuntu):Ubuntu

**Comment by GeorgDangl** [comment]
We're having the same issue, using the cyan 600 color as primary, button color (text and icons) is black. It used to be white before.

However, I've noticed that using a slightly darker cyan 700, the color seems to work again. But, then the primary color is off, of course😀

**Comment by sergidt** [comment]
Same issue, and breaking all my product styles and need to be overwritten, forcing colors hardcoding rules

**Comment by inlym** [comment]
Notify me if resolved.

**Comment by davidpawar** [comment]
Also facing the same issue.

**Comment by johnnygerard** [comment]
Same issue.

**Comment by pqt-tmeitz** [comment]
are there any updates yet?

**Comment by Frankitch** [comment]
Same issue for me, my workaround:
```
.mat-mdc-unelevated-button.mat-primary,
.mat-mdc-unelevated-button.mat-accent {
  --mdc-filled-button-label-text-color: var(--player-primary-contrast-500);
}

.mat-mdc-raised-button.mat-primary,
.mat-mdc-raised-button.mat-accent {
  --mdc-protected-button-label-text-color: var(--player-primary-contrast-500);
}
```

**Comment by MichalK6677** [comment]
The problem is still there. The Angular Material v15 is not usable for more than 2 months.

**Comment by bjoernboehnke** [comment]
Just as an information for others facing an issue like this:
There seems to be a change affecting "unthemed" buttons. A button in my application changed text-color after upgrading to angular material 15 from white to black. It is placed on a dark background. I found this issue and assumed it was caused by this. Just give it a try and give your button a color attribute if it has none and select primary, accent or warn depending on your background. You can use mat-flat-button and then the correct contrast color is selected.
Definitely not a solution for everybody but worked for me.

**Comment by angelaki** [comment]
Any chance this will get fixed soon? I need my contrast color to get used because our CI uses a white font on a pretty light blue. Now all the buttons etc. have a black text.

**Comment by mvanderlee** [comment]
More details here: https://github.com/angular/components/issues/26153

**Comment by sonphnt** [comment]
the same issue to me as well, contrast color does not work.

**Comment by Geniewave** [comment]
same issue here

**Comment by ChristianKohler** [comment]
Same issue. As @beckerjohannes mentioned above, the issue is that for buttons the contrast color is not used. Instead the `on-primary` color from material/theme is applied. 

The `on-primary` color is used for the button text color.

https://github.com/angular/components/blob/96aadaa411a3af93626af9aa73fb4abd6600d0b3/src/material/button/_button-theme.scss#L50

Now `on-primary` is defined here:

https://github.com/material-components/material-components-web/blob/cedffb44c0c5e2b6aeca591b4e5d19346a52983c/packages/mdc-theme/_theme-color.scss#L137

```

@function tone($color) {
  $minimumContrast: 3.1;

  $lightContrast: contrast($color, white);
  $darkContrast: contrast($color, rgba(black, 0.87));

  @if ($lightContrast < $minimumContrast) and ($darkContrast > $lightContrast) {
    @return 'light';
  } @else {
    @return 'dark';
  }
}

@function contrast-tone($color) {
  @return if(tone($color) == 'dark', 'light', 'dark');
}


$on-primary: if(contrast-tone($primary) == 'dark', #000, #fff) !default;
```

As you can see, the minimal contrast is hardcoded. Depending on the contrast the tone is set to `light` or `dark` and depending on the tone the text color is set to white or black.

**Comment by jnain** [comment]
Same issue here. Hope it'll get fixed soon! :)

Thank you @Frankitch for the workaround!

**Comment by ProjectBay** [comment]
Same with checkboxes

**Comment by AlvaroP95** [comment]
Angular 16 is already live, and this is not fixed. Any news on this?

**Comment by aponski** [comment]
I have the same problem with buttons and checkboxes. Contrast color of my custom theme is not applied correctly.

**Comment by Leccho** [comment]
Most of the Angular Material Components don't work properly for the color. I don't know how this as not been fix already. Should have been fix first week after the release of v15, yet here we are at v16 and the problem persist.

**Comment by marc-wilson** [comment]
Same thing in 16.1.5 with chips

**Comment by DeanPDX** [comment]
> Same thing in 16.1.5 with chips

Yeah - it doesn't appear to be getting fixed (I think they might view it as a feature rather than a bug; because it DOES enforce a certain level of contrast, which helps with accessibility). I just targeted the elements I cared about with CSS in my global styles and moved on.

**Comment by sebastianhaberey** [comment]
Same issue. Just posting here as a vote to fix this.

**Comment by Davidihl** [comment]
I set up a fresh angular in the newest version in combination with material.
While trying to setup a custom theme, I noticed that the issue still persists :(

**Comment by danieljohnson107** [comment]
I'm having the same issue using `angular 16.1.0` and `angular material 16.2.1`. This only an issue when defining your own palette, the contrast colors work correctly if you use one of the predefined palettes from angular material.

**Comment by AlirezaEbrahimkhani** [comment]
Same issue using `angular material 16.2.1` and `angular 16.0.4`

**Comment by sanurah** [comment]
Same issue. Can someone tell us if this is not considered as a bug?

**Comment by WasiakSzymon** [comment]
Same issue here using `angular material 16.2.5`

**Comment by sergidt** [comment]
It looks like they are not supporting it. I am thinking to change the UI kit.

**Comment by Bernoulli-IT** [comment]
Sadly 😢 mat-flat-button as well as mat-raised-button still have this, fairly easy to fix imho, issue. Please get back to us with an explanation and/or fix. Greatly appreciated 👍🏼

**Comment by josegomez** [comment]
Is there any update on this? Having the same issue. Anyone have a work-around that doesn't require me to hard code css?

**Comment by mKoranae** [comment]
Would love to know as well. I've been looking for workarounds for days and none really seem to work for all components that the primary color doesn't get used at anymore. Super frustrating :(... Angular 17 will get released soon, I'd hate not to be able to use that version either.

**Comment by PhilippeMorier** [comment]
Same issue. Similar to https://github.com/angular/components/issues/26056#issuecomment-1412183516 but I am reading the contrast value from the specific palette of the theme.

```scss
@mixin theme($theme) {
  button,
  a {
    @include -colors($theme);
  }
}
```

```scss
@mixin -colors($theme) {
  $color-config: mat.get-color-config($theme);
  $primary-palette: map.get($color-config, primary);
  $accent-palette: map.get($color-config, accent);
  $nominal-palette: map.get($color-config, nominal);
  
  $colors: (
    primary: $primary-palette,
    accent: $accent-palette,
    nominal: $nominal-palette
  );
  
  &[mat-flat-button],
  &[mat-raised-button],
  &[mat-fab],
  &[mat-mini-fab] {
    @each $color, $palette in $colors {
      &.mat-#{$color} {
        // https://github.com/angular/components/issues/26056
        --mdc-protected-button-label-text-color: #{mat.get-color-from-palette($palette, '500-contrast')};
        --mdc-filled-button-label-text-color: #{mat.get-color-from-palette($palette, '500-contrast')};
        --mat-mdc-fab-color: #{mat.get-color-from-palette($palette, '500-contrast')};
      }
    }
  }
}
```

**Comment by Davidihl** [comment]
> Would love to know as well. I've been looking for workarounds for days and none really seem to work for all components that the primary color doesn't get used at anymore. Super frustrating :(... Angular 17 will get released soon, I'd hate not to be able to use that version either.

Only workaround I know of so far is manually fixing it e.g. by overwriting the affected classes in global `styles.scss`. Keep in mind to not only change the text-color, you also need to target the ripple effect color.

```scss
// *** Contrast fix example of custom accent color ***
.mat-mdc-raised-button.mat-accent,
.mat-mdc-unelevated-button.mat-accent,
.mat-mdc-fab.mat-accent,
.mat-mdc-mini-fab.mat-accent {
  color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  ) !important;
  --mat-mdc-button-persistent-ripple-color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  ) !important;
  --mat-mdc-button-ripple-color: rgba(255, 255, 255, 0.1); //insert custom rgba contrast color
}

.mat-mdc-fab.mat-accent,
.mat-mdc-mini-fab.mat-accent {
  --mdc-fab-icon-color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  );
  --mat-mdc-fab-color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  );
}
``` 

So far I found that checkboxes are also affected, but I was able to fix it by overwriting like this:

```scss
* {
  --mdc-checkbox-selected-checkmark-color: #fff !important; //using mat.get-color-from-palette() doesn't work for me so I hardcoded the color
}
```

I hope this helps as it did for me.

Bugged:
![image](https://github.com/angular/components/assets/111972510/03a5671e-b3aa-4e0f-a2bc-3eeb0b301ef6)

Fixed:
![image](https://github.com/angular/components/assets/111972510/a4e7bc60-52d9-4ca2-a374-db192a3d4e3f)
