### ISSUE TITLE
feat(material/select): Allow customizing arrow icon

### ISSUE THREAD

**Issue by acohenOT** [angular/components#26090]
### Feature Description

In mat-select component, allow for easily swapping out the arrow icon with a custom one. This was possible in material v14 by overriding CSS properties but now there doesn't seem to be a way to do this in v15 after the switch to MDC components.

### Use Case

UX and branding guidelines may require specific svg icons be used, including the ability the style hover and active states.

**Comment by mmalerba** [comment]
This isn't something we plan to officially support, but there's no reason you can't use custom CSS just like in previous versions. The classes you target are different now because the MDC-based components use different class names.

e.g. something like this:
```scss
.mat-mdc-select-arrow-wrapper {
    background: url('your-icon-here');
    width: 20px;
    height: 20px;
 }
```

But again, stuff like this is use at your own risk. It's not something we officially support
