### ISSUE TITLE
bug(form-field outline, v15 mdc, RTL): Wrong outline color in RTL when form-field input is disabled/focused

### ISSUE THREAD

**Issue by anisabboud** [angular/components#26115]
### Is this a regression?

- [X] Yes, this behavior used to work in v14

## Description

Notice how the outline of a disabled datepicker with `dir="rtl"` isn't fully grayed out:
![image](https://user-images.githubusercontent.com/5672108/204502634-7d8bfc56-aaeb-4879-8a6d-e34a282f3569.png)

The issue also affects regular form-fields with disabled `<input matInput>` / `<mat-select>`.

## Cause

In LTR, the disabled border-color is set after the border-left property, so it works fine, but in RTL, they are set in opposite order (perhaps due to higher specificity of the CSS rule), causing the border-right property to override border-color.

![image](https://user-images.githubusercontent.com/5672108/204504953-e6b6d8db-b3b7-4346-8ab3-dd5fa47101da.png)

## Suggested solution
Consider replacing `border-right: 1px solid;` with individual properties to avoid implicitly setting `border-right-color` as part of `border-right`. I.e., consider replacing:
```scss
[dir=rtl] .mdc-notched-outline__leading, .mdc-notched-outline__leading[dir=rtl] {
        border-right: 1px solid;  <--
}
```
With:
```scss
[dir=rtl] .mdc-notched-outline__leading, .mdc-notched-outline__leading[dir=rtl] {
    border-left: none;
    border-right-width: 1px;    <--
    border-right-style: solid;  <-- 
}
```
(and similarly for the left side)

## Temporary workaround

Global CSS:
```scss
// Temporary workaround for bug https://github.com/angular/components/issues/26115.
.mdc-text-field--disabled .mdc-notched-outline__leading, .mdc-text-field--disabled .mdc-notched-outline__trailing {
  border-color: rgba(0, 0, 0, 0.06) !important;
}
```

## Reproduction

1. Angular Material v15 (mdc components)
2. dir="rtl"
3. `<mat-form-field appearance="outline">`
4. disabled input/select/datepicker

```html
<div dir="rtl">
  <mat-form-field appearance="outline">
    <input matInput [matDatepicker]="datepicker" disabled [(ngModel)]="date">
    <mat-datepicker-toggle matSuffix [for]="datepicker"></mat-datepicker-toggle>
    <mat-datepicker #datepicker [disabled]="false"></mat-datepicker>
  </mat-form-field>
</div>
```

### Expected Behavior

Gray outline.

### Actual Behavior

Partially gray and partially black outline.

### Environment

- Angular: `15.0.1`
- CDK/Material: `15.0.0`

**Comment by anisabboud** [comment]
This is reproducible on https://material2-dev.firebaseapp.com/mdc-input 
Switch to **RTL**, then scroll down and click the checkbox "Disable textarea form-fields".

![image](https://user-images.githubusercontent.com/5672108/204512680-d18ce018-4033-4f6c-ac8d-1d84e9361206.png)

**Comment by anisabboud** [comment]
A similar but different issue is observed when a form-field is **focused** (not disabled):
The side borders are 1px thick instead of 2px, again due to the order of which CSS rules are being applied.

![image](https://user-images.githubusercontent.com/5672108/204532282-a4038a92-7b7c-41c9-a14c-5def28ae2860.png)
https://material2-dev.firebaseapp.com/mdc-input -> toggle RTL -> scroll down to "Outline appearance" and focus on the field.

### Suggested solution
Consider using `border-inline-start` & `border-inline-end` instead of `border-left` & `border-right`.
This way the RTL rules can be removed and won't cause the issue.
https://caniuse.com/mdn-css_properties_border-inline-start
![image](https://user-images.githubusercontent.com/5672108/204533803-e9924b2e-7876-40bd-92bb-78ae9e899aa7.png)

### Temporary workaround
```scss
.mdc-text-field--focused .mdc-notched-outline__leading, .mdc-text-field--focused .mdc-notched-outline__trailing {
  border-width: 2px !important;
}
```
