### ISSUE TITLE
bug(material/table): mouse hover not working with indigo & pink

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#26203]
### Description

![Animation](https://user-images.githubusercontent.com/12090931/206264854-b1c52532-2038-461b-8197-ccadb8795629.gif)

You can check at the table examples in material.io:
https://material.angular.io/components/table/examples

- [X] Deep-purple & Amber
- [ ] Indigo & Pink
- [X] Pink & Blue-Grey
- [X] Purple & Green

The talbe hovering effect doesn't work with Indigo & Pink theme.
Custom light-theme seens to not being working too.

Example:
![image](https://user-images.githubusercontent.com/12090931/206263237-3ca6165c-6abc-43dd-9ef4-b94886f52da7.png)

### Reproduction

Steps to reproduce:
1. Select in material.io table examples the indigo and pink theme
2. Hover over the row and nothing happens.
3. Select in material.io table examples the deeo purple and amber theme
4. Hover over the row, and the styling is applied.

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome and Firefox

**Comment by ChristofferGersen** [comment]
I expect the hover not to be visible, given the following lines from table.scss
```scss
// Disable hover styling while MDC uses an opacity for its color.
// When the hover style is used with sticky cells, the opacity shows the cells overlapping.
.mat-mdc-table .mat-mdc-row:hover,
.mat-mdc-table .mat-mdc-footer-row:hover {
  background-color: inherit;
}
```

This does not always work, since it has the same specificity als the mdc theme selector:
`.mdc-data-table__row:not(.mdc-data-table__row--selected):hover`

As a result the styles apply in declaration/load order. "Indigo & Pink" is probably the default theme, and the other themes are loaded later on demand. Since loading another theme does not include table.scss again, the mdc theme will enable mouse hover again.
