### ISSUE TITLE
bug(thypography): migration to v15 error with `mat.define-legacy-typography-config` conversion

### ISSUE THREAD

**Issue by tchandelle** [angular/components#26278]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When upgrading from v14 to v15, conversion of `mat.define-typography-config()` to `mat.define-legacy-typography-config()` is broken.

### Reproduction

Steps to reproduce:
1. Have a component scss in v14 like:
````scss
@use '@angular/material' as mat;
.foo {
  $typo: mat.define-typography-config();
  > h3 {
    @include mat.typography-level($typo, subheading-2);
  }
}
````
The component is declared as:
````ts
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.scss'],
  encapsulation: ViewEncapsulation.None,
}
```` 

2. Upgrade to v15 with `npx ng update -C @angular/material@15`

### Expected Behavior

Should be converted to `$typo: mat.define-legacy-typography-config();`

### Actual Behavior

Converted instead to `$typo: mat.define-legacy-typography-configmat.define-legacy-typography-config();`

Some are even converted to `$typo: mat.define-legacy-typography-configmat.define-legacy-typography-configmat.define-legacy-typography-configmat.define-legacy-typography-configmat.define-legacy-typography-config();`.

It seems the number of repetition correlate with the number of level in the scss:
````scss
.foo {
  // 1st level > repeated 2 times
  $typo: mat.define-legacy-typography-configmat.define-legacy-typography-config();
  .bar {
    // 2nd levels > repeated 3 times
    $typo: mat.define-legacy-typography-configmat.define-legacy-typography-configmat.define-legacy-typography-config();
  }
}
````

### Environment

- Angular: 15.0.4 (migrated from 14.2.10)
- CDK/Material: 15.0.3 (migrated from (14.2.7)
- Operating System (e.g. Windows, macOS, Ubuntu): darwin x64
- Node: 18.12.1
- Package Manager: yarn 3.1.1
