### ISSUE TITLE
bug(typography): h4 not using subtitle-2 as described in the docs

### ISSUE THREAD

**Issue by webmichelle** [angular/components#26351]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

[Here](https://material.angular.io/guide/typography#typography-levels) in the table the documentation states that `subtitle-2` is corresponding to the `<h4>`. I found that the `<h4`> tag is actually using the `body-1` styling as you can see in the following code snipped copied from the `_typography.scss` file.
```css
  .mat-h4,
  .mat-body-1,
  #{$selector} .mat-h4,
  #{$selector} .mat-body-1,
  #{$selector} h4 {
    @include typography-utils.typography-level($config, body-1);
    margin: 0 0 16px;
  }
```

and subtitle-2 is not corresponding to any heading:

```css
  .mat-body-strong,
  .mat-subtitle-2,
  #{$selector} .mat-body-strong,
  #{$selector} .mat-subtitle-2 {
    @include typography-utils.typography-level($config, subtitle-2);
  }
```

### Reproduction

* Define a custom typography config with `mat.define-typography-config`
* Define `$subtitle-2`
* Use a `<h4>` tag in your template (with or without explicitly defining the class `mat-h4` on the element)
* Style of `subtitle-2` is not applied to the `<h4>` tag. 

### Expected Behavior

`<h4>` tags should either use `subtitle-2` or the documentation should be updated 

### Actual Behavior

`<h4>` is using `body-1` styling

### Environment

- Angular: 15.0.3
- CDK/Material: 15.0.3
- Browser(s): Chromium based (Brave, Chrome)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu
