### ISSUE TITLE
bug(chip): Overflow visible on action chips text break chip design and usability

### ISSUE THREAD

**Issue by MikaStark** [angular/components#26584]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

This CSS rule https://github.com/angular/components/blame/01d5a9d12cad72a2c2bb6f71baf145d0ff4af13a/src/material/chips/chip.scss#L131 override MDC chip label overflow hidden to visible.

@crisbeto put this comment above the rule

```scss
  // MDC sets `overflow: hidden` on these elements in order to truncate the text. This is
  // unnecessary since our chips don't truncate their text and it makes it difficult to style
  // the strong focus indicators so we need to override it.
  .mdc-evolution-chip__cell--primary,
  .mdc-evolution-chip__action--primary,
  .mat-mdc-chip-action-label {
    overflow: visible;
  }
```

But by not truncating chip long text/label, we reduce it usability and get a weird appearance.

As you can see, on small devices, the chip is quiet broken and the trailing icon cannot be reached (which is terrible)

![image](https://user-images.githubusercontent.com/23034761/217331103-52a22bea-a4d4-4658-80cd-fac2a3f89791.png)

By just removing the CSS rule, we get the perfect behavior IMO

![image](https://user-images.githubusercontent.com/23034761/217331433-bd5a50a7-737f-4aa8-932b-71cb0f5794d7.png)

### Reproduction

Steps to reproduce:
1. Go to https://material.angular.io/components/chips/examples
2. Reduce your viewport size to 425px (on Chrome it's equivalent to Mobile L)
3. On the first example, focus the input, type "This is a very long annoying text that break this chip" and press "Enter"
4. See that the text overflow and the trailing icon is not reachable

### Expected Behavior

Remove the CSS rule here : https://github.com/angular/components/blame/01d5a9d12cad72a2c2bb6f71baf145d0ff4af13a/src/material/chips/chip.scss#L13

### Actual Behavior

![image](https://user-images.githubusercontent.com/23034761/217333439-738d6cf7-d071-4ab5-90d0-9c4e7f37c8f4.png)

### Environment

- Angular: 15.1.3
- CDK/Material: 15.1.3
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by ahbuddha** [comment]
Thank you for this!!!
My work around:
```
:host ::ng-deep .mat-mdc-standard-chip .mdc-evolution-chip__cell--primary,
:host ::ng-deep .mat-mdc-standard-chip .mdc-evolution-chip__action--primary,
:host ::ng-deep .mat-mdc-standard-chip .mat-mdc-chip-action-label {
    overflow: hidden;
}
```

**Comment by raysuelzer** [comment]
Also this will remove any fontawesome icons or anything that uses the before psuedoselector. https://github.com/angular/components/blame/f0a5008b237d4bde3e8d759ca9e793c164656d7a/src/material/chips/chip.scss#L320-L322

**Comment by wagnermaciel** [comment]
Bumping priority since there is no supported workaround and this issue has also come up internally

**Comment by Siddhu-K** [comment]
I am using the following css overides to fix the issue. this works well when the text need to wrap instead of having overflow:hidden, the chip height will increase accordingly. 

`.mdc-evolution-chip__text-label {
  white-space: normal !important;
  line-height: normal !important;
}

.mat-mdc-chip {
  height: fit-content !important;
  padding-top: 7px !important;
  padding-bottom: 7px !important;
}`

**Comment by MikaStark** [comment]
Here is my workaround, it doesn't require `!important`

```scss
.mdc-evolution-chip-set .mat-mdc-standard-chip {
  .mdc-evolution-chip__cell--primary,
  .mdc-evolution-chip__action--primary,
  .mat-mdc-chip-action-label {
    overflow: hidden;
  }
}
```
