### ISSUE TITLE
Button - touch height

### ISSUE THREAD

**Issue by leomayer** [angular/components#27118]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The `height` of the `touch-target` for buttons is fixed with `48px`. If the corresponding button has the standard-height of `48px` than this is fine. With reducing e.g. the `denisity` the `48px` shrink to e.g. `36px`. Therefore the `height` should rather `inherit` the height from the button instead of its own fixed height.

The main problem is that the surrounding layout container calculates the height of the button as `36px`. The button don't fit into and an `overflow` appears.

### Reproduction

The provided sample container could be adjusted with the proper css attributes. Nevertheless the problem persists in some other configurations especially when the minimal height is calculated wrongly.

https://stackblitz.com/edit/nxq1bh?file=src/app/button-overview-example.css

### Expected Behavior

```
.mat-mdc-button .mat-mdc-button-touch-target, .mat-mdc-unelevated-button .mat-mdc-button-touch-target, .mat-mdc-raised-button .mat-mdc-button-touch-target, .mat-mdc-outlined-button .mat-mdc-button-touch-target {
    position: absolute;
    top: 50%;
    height: inherit;
    left: 0;
    right: 0;
    transform: translateY(-50%);
}

### Actual Behavior

```
.mat-mdc-button .mat-mdc-button-touch-target, .mat-mdc-unelevated-button .mat-mdc-button-touch-target, .mat-mdc-raised-button .mat-mdc-button-touch-target, .mat-mdc-outlined-button .mat-mdc-button-touch-target {
    position: absolute;
    top: 50%;
    height: 48px;
    left: 0;
    right: 0;
    transform: translateY(-50%);
}
```

### Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.2
Node: 20.1.0 (Unsupported)
Package Manager: npm 9.6.4
OS: linux x64

Angular: 16.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1600.2
@angular-devkit/build-angular      16.0.2
@angular-devkit/core               16.0.2
@angular-devkit/schematics         16.0.2
@angular/cdk                       16.0.1
@angular/material                  16.0.1
@angular/material-moment-adapter   16.0.1
@schematics/angular                16.0.2
typescript                         4.9.5

**Comment by LittleSaya** [comment]
This happens to me when I put a button as footer inside a dialog, there is always a y-scrollbar

**Comment by Renji-FR** [comment]
What is the status of this issue? I have the same behavior.

I tried to set `--mdc-icon-button-state-layer-size` to the right height but the `touch-target` height stays to 48px.

**Comment by mohammedsahl** [comment]
> This happens to me when I put a button as footer inside a dialog, there is always a y-scrollbar

Likewise :(

For now I've decided to unset the height using
```scss
.footer,
mat-dialog-actions {
  ::ng-deep span.mat-mdc-button-touch-target {
    height: unset;
  }
}
```
Pros: No scrollbar

Cons: Uses the [hotly debated ng-deep](https://github.com/angular/angular/issues/25160). Slightly less accessible

**Comment by devAnky** [comment]
This is still an issue in version 17.3!

**Comment by FlepTheFlabbergasted** [comment]
Still an issue as well!

**Comment by arthurfaby** [comment]
Up :)

**Comment by roma2341** [comment]
Buttons are broken, they always make my parent think that it's overflowing..

**Comment by PowerKiKi** [comment]
`matIconButton`, `matButton`, `mat-radio-button` and `mat-slide-toggle` all suffers from that issue.

`matIconButton` is probably the worst offender because two `matIconButton` side by side will visually align, but their touch target will overlap, as shown below.  The cyan background is `matIconButton` bounds of visible elements (with the hover effect forced via devtools). The red border shows the bounds of touch targets and illustrate how both **touch targets overlap each other**. That becomes an accessibility issue, because your mouse might be visually over the first icon, but it will actually be over the touch target of the second icon. So you **might click the wrong button**.

<img width="214" height="140" alt="Image" src="https://github.com/user-attachments/assets/70a58026-c0e1-441f-9697-05e2cb34eab4" />

My workaround for this, and other elements, is the following. In the case of icons, the icons themselves are bigger, to match touch targets. Other elements have their touch targets reduced (but not hidden), against MD3 recommendations, but we cannot break layout everywhere just to follow that recommendation, and since all those other elements have text labels that makes the elements naturally wider (but not higher), it should still be reasonably touchable.

```scss
@use '@angular/material' as mat;

html {
    // Make icon buttons bigger, same as before MD3, so their visual size match their touch target. And we avoid scrolling.
    @include mat.icon-button-overrides(
        (
            state-layer-size: 48px,
        )
    );

    // Reduce touch target size for buttons. Otherwise their touch targets would create scrolling.
    // And it should still be fine to touch because they are naturally bigger because of their labels.
    @include mat.button-overrides(
        (
            text-touch-target-size: 40px,
            protected-touch-target-size: 40px,
            outlined-touch-target-size: 40px,
            filled-touch-target-size: 40px,
            tonal-touch-target-size: 40px,
        )
    );

    // Reduce touch target size for radio buttons. Otherwise their touch targets would create scrolling.
    // And it should still be fine to touch because they are naturally bigger because of their labels.
    @include mat.radio-overrides(
        (
            touch-target-size: 40px,
        )
    );

    // mat-slide-toggle is slightly higher than before MD3, so we can see their ripple entirely. And the
    // touch target is the same as before MD3. But the touch target should be fine because the label
    // naturally increase the touch surface (and we never had issue in the past).
    @include mat.slide-toggle-overrides(
        (
            touch-target-size: 40px,
        )
    );
    .mdc-switch {
        height: var(--mat-slide-toggle-touch-target-size);
    }
}
```
