### ISSUE TITLE
bug(MatFormField): Changing typography config font size leads to an unexpected spacing of a value

### ISSUE THREAD

**Issue by Mesya82** [angular/components#28170]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When defining a custom typography config and decreasing the size of body-1 element, MatFormField input text value is not spaced in the middle of a field.

### Reproduction

[StackBlitz link](https://stackblitz.com/edit/yvqvqg?file=src%2Ftheme.scss,src%2Fexample%2Fform-field-overview-example.ts)
Steps to reproduce:
1. Create a custom theme a provide custom typography config, which defines 14px font-size for "body-1" element
2. Use MatFormField as you would usually and input something in the field

### Expected Behavior

The input field value is positioned in the middle vertically within the field

### Actual Behavior

The input field value is positioned not in the middle with the offset to the top
![image](https://github.com/angular/components/assets/32867735/4175974a-0419-40a5-90f5-f088feb4b7be)

### Environment

- Angular: >= 16.2.7
- CDK/Material: >= 16.2.12
- Browser(s): Edge 119.0.2151.72
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 19045.3570

**Comment by Mesya82** [comment]
Currently, as a workaround, I've added this rule to the global styles to "fix" that:
```scss
  .mat-mdc-form-field .mat-mdc-text-field-wrapper.mdc-text-field .mat-mdc-form-field-flex .mat-mdc-form-field-infix {
    display: flex;
    align-items: center;
  }
```
