### ISSUE TITLE
feat(dialog): set default actions alignment with injection token

### ISSUE THREAD

**Issue by json-derulo** [angular/components#28302]
### Feature Description

I want the dialog actions to be aligned to the right by default. Currently this is not part of the [`MatDialogConfig`](https://material.angular.io/components/dialog/api#MatDialogConfig), so it cannot be set via the `MAT_DIALOG_DEFAULT_OPTIONS` injection token. It cancan only be achieved by setting the `align` input for each usage of the [`mat-dialog-actions`](https://material.angular.io/components/dialog/api#MatDialogActions) component:

```html
<mat-dialog-actions align="end">
</mat-dialog-actions>
```

My suggestion is to add an optional `alignActions` property to the `MatDialogConfig` interface to control the default alignment.

### Use Case

The actions alignment should be changeable at a single point, so it is easier to maintain in larger code bases.

**Comment by json-derulo** [comment]
Since v19, this can be achieved with the [overrides mixin](https://material.angular.io/components/dialog/styling):

```scss
@use '@angular/material' as mat;

:root {
  @include mat.dialog-overrides((
    actions-alignment: flex-end,
  ));
}
```
