### ISSUE TITLE
bug(expansion panel): toggle does not have a border-color set explicitly.

### ISSUE THREAD

**Issue by liesahead** [angular/components#28597]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Currently there are such styles for expansion panel toggle

```CSS
.mat-expansion-indicator::after {
    ...
    color: var(--mat-expansion-header-indicator-color);
    ...
}
```

But in our case (we use tailwind CSS) we have such global styles (note that it has lower specificity):
```CSS
*, ::before, ::after {
    border-color: #e5e7eb;
}
```

And these styles override the color of the toggle because it's actually a `border`. To fix that I had to apply such global style:
```CSS
.mat-expansion-indicator::after {
    border-color: currentcolor;
}
```

### Reproduction

Steps to reproduce:
1. Add expansion panel component to the page
2. Set such global styles for the app
```CSS
*, ::before, ::after {
    border-color: red;
}
```
3. See that expansion panel toggle has become red

### Expected Behavior

Expansion panel toggle should have such style included (note `border-color: currentColor`)
```CSS
.mat-expansion-indicator::after {
    ...
    color: var(--mat-expansion-header-indicator-color);
    border-color: currentcolor;
    ...
}
```

### Actual Behavior

There's no styling for the border color.

### Environment

Angular CLI: 17.1.3
Node: 18.14.0
Package Manager: yarn 3.6.4
OS: win32 x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@angular/cdk                    17.1.2
@angular/material               17.1.2
@schematics/angular             17.1.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
