### ISSUE TITLE
docs-bug(theming): Change components theming guide to encourage css custom properties

### ISSUE THREAD

**Issue by MikaStark** [angular/components#28612]
### Documentation Feedback

Hi 🖖
Since v17.2.0, Material 3 is experimentally supported and you.

I propose aligning the "@angular/material Theming your components" guide with the Material 3 philosophy by emphasizing the use of CSS custom properties over selectors and conventional CSS rules. As you are aware, Material 3 for the web heavily relies on CSS custom properties, and this adjustment would be more in line with the framework's theming approach.

The suggested change aligns with Material 3's philosophy of emitting only CSS custom property declarations, avoiding standard CSS properties (refer to https://material.angular.io/guide/material-3#applying-your-theme). Importantly, this approach remains fully compatible with the current Material 2 themes implementation.

Furthermore, incorporating CSS custom properties will streamline the organization of CSS rules by allowing them to be centralized directly in the component's stylesheet. This centralization mitigates the challenges associated with splitting rules across multiple files, resulting in a more manageable and less error-prone maintenance process. It is worth noting that this approach enhances component autonomy, making theming optional, as custom properties can be set outside of a theme. This flexibility ensures a smoother development and maintenance experience.

Implementing this proposal would greatly assist developers in their future migration from Material 2 to 3, requiring only changes to flat custom properties isolated in mixins. Additionally, it opens the door to granular customizations with CSS custom properties (see https://material.angular.io/guide/material-3#granular-customizations-with-css-custom-properties) even before material 3 integration becomes stable. Embracing CSS custom properties aligns with modern best practices and ensures future-proofing.

Thank you for considering this proposal.

Example : 

```scss
// carousel.scss

.my-carousel {
  display: flex;
  color: var(--app-carousel-color);
  font-family: var(--app-carousel-font-family);
}

.my-carousel-button {
  border-radius: var(--app-carousel-shape);
}

// _carousel-theme.scss

@mixin color($theme) {
  --app-carousel-color: #{mat.get-theme-color($theme, primary)};
}

@mixin typography($theme) {
  --app-carousel-font-family: #{mat.get-theme-typography($theme, headline-1)};
}
```

### Affected documentation page

https://material.angular.io/guide/theming-your-components
