### ISSUE TITLE
bug(mat-slide-toggle): disableRipple not causing any visual changes

### ISSUE THREAD

**Issue by amysorto** [angular/components#28679]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

 It looks like `disableRipple` was used to prevent the ripple animation (ripple based on where in the touch target you clicked) in the legacy components, but now that doesn't seem to show up anymore. So it seems that setting `disableRipple` isn't causing any difference now.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/aakbph?file=src%2Fexample%2Fslide-toggle-overview-example.html

### Expected Behavior

Setting `disableRipple` to true would cause a visual difference upon clicking the slide toggle handle.

### Actual Behavior

No viusal change

### Environment

- Angular: 17.2.0-rc.0
- CDK/Material: 17.2.0-rc.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by burmanp** [comment]
Any more update on this? `disableRipple` doesn't work on sliders either.
I deal with it using css for now like so
```css
.mat-mdc-slider { 
  --mat-mdc-slider-hover-ripple-color: unset; // 'none' also works
  --mat-mdc-slider-focus-ripple-color: unset;
}
```
