### ISSUE TITLE
bug(styles): mdc-icon-button-state-layer-size is not globally available anymore

### ISSUE THREAD

**Issue by Casimodo72** [angular/components#28738]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

7.1.2

### Description

The generated styles.css does not contain the CSS variable (property) "mdc-icon-button-state-layer-size" under "html" anymore.

In my apps I'm using that variable to calculate the half of an icon-button's height.
How are we supposed to know the size of an icon-button now? Is there a different variable available?

### Reproduction

Build apps with Angular Material 7.1.2 and 7.2.2 (or 7.3.0). In the latter version, inspect the missing CSS variable "mdc-icon-button-state-layer-size" under "html".

### Expected Behavior

In an earlier version (7.1.2) we had this variable defined under hmlt:
```scss
html {
  // ... other non-icon-button tokens
  // In version 7.1.2 we *have* "mdc-icon-button-state-layer-size":
  --mdc-icon-button-state-layer-size: 48px;
  --mdc-icon-button-icon-size: 24px;
  --mdc-icon-button-icon-color: inherit;
  // ... more "--mdc-icon-button-xyz" variables
}
```

And we were able to use that variable globally in order to calculate stuff. E.g.:
```scss
:root {
    --half-button-size: calc(0.5 * var(--mdc-icon-button-state-layer-size));
    --half-button-negative-size: calc(-1* 0.5 * var(--mdc-icon-button-state-layer-size));
}
```

### Actual Behavior

In (7.2.2 and 7.3.0) we don't have this variable anymore in the generated styles.css:
```scss
html {
  // ... other non-icon-button tokens
  // NOTE: In 7.2.2 (and 7.3.0) this is missing the "mdc-icon-button-state-layer-size" variable.
   --mdc-icon-button-icon-size: 24px;
  --mdc-icon-button-icon-color: inherit;
  // ... more "--mdc-icon-button-xyz" variables
}
```

### Environment

- Angular: 7.1.2
- CDK/Material: 7.3.0
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows
