### ISSUE TITLE
feat(material/theming): fine-grain token override

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#28929]
### Feature Description

Add a mixin to our components theming API which emits CSS to override the CSS variables emitted by our existing API.

This design satisfies the following pain points for our users:
- There are no guard rails preventing users from misspelling variable names.
- Our CSS variables are prefixed with "--mat" and "--mdc" which can be confusing for users.

### Use Case

Any situation where a user would like to override our styles.

#### Example Usage:

```scss
@include mat.checkbox-overrides((
    checkmark-color: red,
));

.my-other-checkbox {
    @include mat.checkbox-overrides((
        checkmark-color: blue,
    ));
}
```

#### Example Output

```scss
html {
    --mdc-checkbox-checkmark-color: red;
}

.my-other-checkbox {
    --mdc-checkbox-checkmark-color: blue;
}
```
