### ISSUE TITLE
feat(material/theming): system-level token override

### ISSUE THREAD

**Issue by wagnermaciel** [angular/components#28931]
#### Part 1

Add a flag to our theming API to output a layer of indirection between our current CSS variables and their values such that our existing css variables map to a smaller subset of system variables.

These system variables correspond to the design-tokens outlined in the [material design spec](https://m3.material.io/foundations/design-tokens/how-to-read-tokens#20829697-fd3d-4802-b295-96ba564f2e50).

#### Part 2

Add a mixin to emit system variables with their values based on a theming config.

This design satisfies the following pain points for our users:
- Tokens are too fine-grained for some common use-cases.

#### Example Usage

```scss
$theme: mat.define-theme((
    color: (..., use-system-level-variables: true),
    density: (...),
    typography: (...),
));

// Emits component css variables mapped to system-level css variables.
html {
    @include mat.all-components-themes($theme);
}

// Emits system-level css variables with their values.
.light-mode {
     @include mat.system-level-colors($theme, overrides: (
         primary: blue,
     ));
}

// Emits system-level css variables with their values.
.dark-mode {
    @include mat.system-level-colors($theme, overrides: (
         primary: white,
     ));
}
```
