### ISSUE TITLE
feat(system-level-variables): Allow calling component mixins without specific theme

### ISSUE THREAD

**Issue by marklagendijk** [angular/components#29374]
### Feature Description

System level CSS variables are awesome. They give full control over theming:
* Theme variable values are available at runtime.
* Theme variable values can be adjusted at runtime.
* Changing the entire theme is just a matter of supplying different values for the `sys-` variables.
* Using any theme variable anywhere in the app can be done using the CSS variables. No need for importing any SASS logic from `@angular/material`.

Defining and using a theme is as simple as:
```scss
@use "@angular/material" as mat;

$theme: mat.define-theme(
  (
    color: (
      theme-type: light,
      primary: mat.$cyan-palette,
      tertiary: mat.$magenta-palette,
      use-system-variables: true,
    ),
    typography: (
      use-system-variables: true,
    ),
  )
);

html {
  @include mat.system-level-colors($theme);
  @include mat.system-level-typography($theme);
}
```

With this one can easily define a bunch of such defined themes, and then load one based on user settings. Alternatively a backend endpoint could render the CSS file with the `sys-` variables.

## The issue
Everything in Angular Material nicely supports system-level themes, except the component theming mixins. 
We still are still required to do something like:
```scss
html {
    @include mat.all-component-themes($theme);
}
```

This is not nice, because we now have generic styling code that needs to use a specific theme. 

A solution would be to allow passing something like this:
```scss
html {
  @include mat.all-component-themes((use-system-variables: true));
  // Or available on mat.
  @include mat.all-component-themes(mat.$system-variables-theme);
  // Or allow passing no theme
  @include mat.all-component-themes();
}
```

### Workaround
Create your own `$system-variables-theme`, and use it:
```scss
html {
  $system-variables-theme: mat.define-theme(
    (
      color: (
        use-system-variables: true,
      ),
      typography: (
        use-system-variables: true,
      ),
    )
  );
  @include mat.all-component-themes($system-variables-theme);
}
```

### Use Case

Easy and clean theming, with minimal theme files.
I'm not sure whether the current workaround is 'ergonomic' enough. If it is, it should at least be added to the documentation.

**Comment by crisbeto** [comment]
Are the changes in https://github.com/angular/components/pull/29275 what you're looking for?

**Comment by marklagendijk** [comment]
@crisbeto I have no clue what that PR is doing. The library and its usage of SASS are so complex / non-common that most code is quite unreadable to those not familiar with it.

My issue is about making system level variables first-class citizens. For me that includes being able to call the mixins without an actual theme being present.
My workaround accomplishes this, but I think it might be more clean if the library accommodates this usecase specifically.

**Comment by crisbeto** [comment]
The PR will add an API that lets you override specific tokens without having to pass in a theme. That being said, with the system-level variables you can already set the values directly. The `system-level-colors` and `system-level-typography` mixins are there primarily to make it easier to generate the tokens if you already have a theme.

**Comment by crisbeto** [comment]
Closing since we're in the progress of documenting a simplified theming API based primarily on system variables.

**Comment by marklagendijk** [comment]
@crisbeto is this documentation available already? Where can I find it?

**Comment by crisbeto** [comment]
Each component has a "Styling" tab in the `next` version of the docs site: https://next.material.angular.io/components/card/styling. After v19 final the docs will be available on the main site as well.

**Comment by marklagendijk** [comment]
@crisbeto are in v19 the default values set to the system variables?
So is it no longer necessary to call `@include mat.all-component-themes`?

```scss
html {
  $system-variables-theme: mat.define-theme(
    (
      color: (
        use-system-variables: true,
      ),
      typography: (
        use-system-variables: true,
      ),
    )
  );
  @include mat.all-component-themes($system-variables-theme);
}
```
