### ISSUE TITLE
bug(stepper): bad contrast of step icon in untouched state

### ISSUE THREAD

**Issue by json-derulo** [angular/components#29518]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using a custom theme, in the stepper it can happen that the step icon (step number or state icon) has a bad contrast:

![image](https://github.com/user-attachments/assets/2d4678c7-7ff1-49c0-a4e3-b972cddf6e0c)

It depends on the contrast color of the primary color. If it's white, everything works correctly, but if it's black, this issue occurs. However for the untouched state, it should always be white, regardless of the contrast color.

Dark mode has the same issue. Here it can even be reproduced in the v16 docs app after selecting the "Purple & Green" theme:

![image](https://github.com/user-attachments/assets/54afc55c-fdf8-423c-a7ce-c17c1f543f56)

I was not able to reproduce this with M3, the predefined themes work fine. I didn't try custom M3 themes though.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/61i1fz?file=src%2Fstyles.scss
Steps to reproduce:
1. Configure a primary color with black as a contrast color in light theme, or white as a contrast color in dark theme
2. Use the stepper

### Expected Behavior

The step icon has sufficient contrast in untouched state

### Actual Behavior

The stepper has insufficient contrast in untouched state

### Environment

Angular CLI: 18.0.2
Node: 18.20.3
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 18.0.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1800.2
@angular-devkit/build-angular      18.0.2
@angular-devkit/core               18.0.2
@angular-devkit/schematics         18.0.2
@angular/cdk                       18.1.2
@angular/cli                       18.0.2
@angular/material                  18.1.2
@angular/material-experimental     18.1.2
@angular/material-moment-adapter   18.1.2
@schematics/angular                18.0.2
rxjs                               7.4.0
typescript                         5.4.5
zone.js                            0.14.6

**Comment by MadunaThabo** [comment]
Hello

it would seem that the header-icon-foreground-color is applied from the theme passed through

![image](https://github.com/user-attachments/assets/b59abb1e-3ece-4f67-9329-c7c6d08b417f)

![image](https://github.com/user-attachments/assets/54f29b02-ac3d-4e48-90a9-47eef98aeffd)


I would recommend just changing the color of the mat-step-icon in your css

**Comment by P4** [comment]
Stumbled upon this today and ended up patching `src/material/stepper/_m2-stepper.scss` to work around it.

It seems very counter-intuitive that `--mat-stepper-header-icon-foreground-color` is not defined together with its corresponding background:
https://github.com/angular/components/blob/3670e0f6c59e5c78a421658b99da07f15c3a1388/src/material/stepper/_m2-stepper.scss#L26

but instead varies depending on the palette (primary/accent/warn) alongside the selected-state colors:
https://github.com/angular/components/blob/3670e0f6c59e5c78a421658b99da07f15c3a1388/src/material/stepper/_m2-stepper.scss#L57-L59

Actual component uses them together:
```css
.mat-step-icon {
    color: var(--mat-stepper-header-icon-foreground-color, var(--mat-sys-surface));
    background-color: var(--mat-stepper-header-icon-background-color, var(--mat-sys-on-surface-variant));
}
```

Defining the two tokens together and setting foreground to `surface` instead of `on-primary` solved the contrast issue for me.

**Comment by dkimmich-onventis** [comment]
This issue also makes it harder to override the header icon foreground color, for example when a custom background color is used. The following does not work correctly in M2:

```scss
:root {
  @include mat.stepper-overrides(
    (
      header-icon-foreground-color: #000,
      header-icon-background-color: #dadada,
    )
  );
}
```

The background color is changed, but the foreground color is overridden via the `mat-primary` class.

It only works when scoping the foreground color override to the `.mat-step-icon` class selector:

```scss
:root {
  @include mat.stepper-overrides((
     header-icon-background-color: #dadada,
  ));

  .mat-step-icon {
    @include mat.stepper-overrides((
      header-icon-foreground-color: #000,
    ));
  }
}
```
