### ISSUE TITLE
bug(navigation): no color on top mat-toolbar on version 18.1.2 (works with v17.3.8)

### ISSUE THREAD

**Issue by arcenik** [angular/components#29523]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v17.3.8

### Description

The top mat-toolbar generated from @angular/material:navigation does not have any color.

The css in v18:
```css
.mat-toolbar.mat-primary[_ngcontent-ng-c3026548424] {
    position: sticky;
    top: 0;
    z-index: 1;
}
```

The css in v17:

```css
.mat-toolbar.mat-primary {
    background: #3f51b5;
    color: #fff;
}
```

### Reproduction

```sh
$ npm install @angular/cli@v18.1.2
$ ./node_modules/.bin/ng new --skip-git myapp
? style format: css (default)
? server-side rendering: no (default)

$  cd myapp
$ ./node_modules/.bin/ng add @angular/material
? prebuilt theme: indigo/pink (default)
? global typography styles: no (default)
? include animation: include and enable (default)

$ ./node_modules/.bin/ng generate @angular/material:navigation main-nav

# Add <ng-content></ng-content> in main-nav.component and replace app.component template by <app-main-nav>Hello World</app-main-nav>

$ ./node_modules/.bin/ng serve
```

### Expected Behavior

How it looks like in v17
![v17-desktop](https://github.com/user-attachments/assets/089deefc-c1e4-4671-9681-7185290b0996)

### Actual Behavior

How it looks like in v18
![v18-desktop](https://github.com/user-attachments/assets/fd3cadda-dd1a-401d-a9a1-3631af073851)

### Environment

- Angular: 18.1.2
- CDK/Material: @angular/cdk@18.1.2 @angular/material@18.1.2
- Browser(s): Brave 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit) 
- Operating System (e.g. Windows, macOS, Ubuntu): Archlinux x64

**Comment by amysorto** [comment]
The mat-toolbar does not have a background color in M3 like it used to in M2. See this example: https://material.angular.io/components/toolbar/examples#toolbar-basic

Although you update the background with custom styles. Changing this CSS variable should allow you to update the background color: `--mat-toolbar-container-background-color`

**Comment by arcenik** [comment]
Is it possible to use mat.get-theme-color function ?
It looks like function are called only for properties, not variables.

```css
:root {
  some-property: mat.get-theme-color($theme, primary, 50);
  --mat-toolbar-container-background-color: rgb(0, 87, 201);
  --mat-toolbar-container-background-color: mat.get-theme-color($theme, primary, 50);
}
```

![image](https://github.com/user-attachments/assets/c3349c00-f278-4145-a93c-58fb04df7fce)
