### ISSUE TITLE
M3 material custom theme (doc+ howto)

### ISSUE THREAD

**Issue by jfduhamel** [angular/components#30141]
### Documentation Feedback

hello angular / material / m3,
where is the official doc of material 3 for angular material ?
it's a nightmare to construct my CUSTOM scss theme since i moved from angular 17 to 19
primary secondary tertiary neutral ...
i only need a primary why it seems i need to give the others secondary .....
nowhere i can find a real example !
https://material.angular.io/ its only about components

oh yeah using a prebuilt theme no souci but the other way...

am i the only one in this situation ?

### Affected documentation page

https://material.angular.io/

**Comment by lucasvanhalst** [comment]
Try `ng generate @angular/material:m3-theme`
You give it a primary color and it spits out a theme file

Which you can then use like this

```scss
html {
  color-scheme: light dark;
  @include mat.theme((
    color: (
      primary: $primary-palette,
      tertiary: $tertiary-palette,
      use-system-variables: true,
    ),
    typography: (
      use-system-variables: true,
    ),
  ))
}
```

I agree that the theming docs are subpar and should be improved a lot.
