### ISSUE TITLE
docs-bug(THEMING): simple M3 Button colour variants example

### ISSUE THREAD

**Issue by tayambamwanza** [angular/components#30267]
### Documentation Feedback

It took me a while but I figured out how to acheive similar behaviour to the color input that m2 had without using `  @include mat.color-variants-backwards-compatibility($theme);`

I chose to use "tertiary" as my "accent"

First I ran 

`npm run ng generate @angular/material:theme-color -- --primary-color '#7AA802' --secondary-color '' --tertiary-color '#276667' --neutral-color '' --include-high-contrast --directory=src/app/styles/`

After that in the styles.scss I added these 2 classes

```scss
// Custom Theming for Angular Material
// For more information: https://material.angular.io/guide/theming
@use '@angular/material' as mat;
@use 'app/styles/theme-colors' as theme;

:root {
  .tertiary {
    @include mat.theme((
      color: theme.$tertiary-palette,
    ));
  }

  .error {
    @include mat.theme((
      color: mat.$red-palette,
    ));
  }
}
```

I then removed the color input from my buttons and then added the appropriate class e.g. (no need to add a primary class as "primary" is the default)

```html
  <button mat-flat-button> View </button>
  <button mat-flat-button class="tertiary"> Close </button>
  <button mat-flat-button class="error"> Delete </button>
```

This restored behaviour similar to the old color input

I believe an example of similar steps would be helpful to those moving over from m2 to m3 as this was the single biggest issue I faced, approx took me a week to work it out, the key paragraph was here, so maybe such an example could be provided there:

https://material.angular.io/guide/theming#context-specific-themes

### Affected documentation page

https://material.angular.io/guide/theming#context-specific-themes
