### ISSUE TITLE
bug( overlay): @layer not work at chrome 78

### ISSUE THREAD

**Issue by linlexing** [angular/components#30270]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18

### Description

old browser not support cascade layers css command,such as @layer.all overlay div not visible, the z-index not set.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

overlay can work

### Actual Behavior

overlay not work,css error

### Environment

- Angular:
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cli                    19.0.6
@schematics/angular             19.0.6
ng-packagr                      19.0.1
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
- CDK/Material:
@angular/cdk                    19.0.4
@angular/material               19.0.4
- Browser(s):
chrome 78.0.3904.70 
- Operating System (e.g. Windows, macOS, Ubuntu):
windows

**Comment by crisbeto** [comment]
Chrome 78 isn't supported. We support the two latest versions of major browsers.

**Comment by linlexing** [comment]
Enterprise development, not all browsers can be upgraded to the latest, the library's compatibility policy is such that it can be said to be bye.

What a blind man to be on a stolen ship. What's the point of the.browserslistrc configuration in angular, guys? Start digging out the material.

**Comment by wartab** [comment]
> Enterprise development, not all browsers can be upgraded to the latest, the library's compatibility policy is such that it can be said to be bye.
> 
> What a blind man to be on a stolen ship. What's the point of the.browserslistrc configuration in angular, guys? Start digging out the material.

Not being able to update browsers is a significantly worse risk than updating browsers to their latest versions. Maybe you can try to push for a change for outdated company policy.

**Comment by linlexing** [comment]
> > Enterprise development, not all browsers can be upgraded to the latest, the library's compatibility policy is such that it can be said to be bye.
> > What a blind man to be on a stolen ship. What's the point of the.browserslistrc configuration in angular, guys? Start digging out the material.
> 
> Not being able to update browsers is a significantly worse risk than updating browsers to their latest versions. Maybe you can try to push for a change for outdated company policy.

The enterprise development I encountered was basically an Intranet environment, and the workstation could not connect to the Internet. Well, it's not windows OS yet, so updating the browser is a huge workload update that requires updating the OS core and graphics card drivers, and it's easy to fail. Finally, the solution is as follows:
```scss
        .cdk-overlay-container {
		z-index: 1000
	}

	.cdk-global-overlay-wrapper {
		z-index: 1000
	}

	.cdk-overlay-pane {
		z-index: 1000
	}

	.cdk-overlay-backdrop {
		z-index: 1000;
		transition: opacity 0ms cubic-bezier(0.25, 0.8, 0.25, 1) !important;//disable transition ANIMATIONS
	}

	.cdk-overlay-dark-backdrop {
		background: rgba(0, 0, 0, .32)
	}

	.cdk-overlay-connected-position-bounding-box {
		z-index: 1000
	}

```
