### ISSUE TITLE
docs-bug(ALL): No examples of how to apply theme

### ISSUE THREAD

**Issue by alanpurple** [angular/components#30353]
### Documentation Feedback

there is no way to apply defined primary, secondary, error, etc   color to components

for one, there is no example how to apply secondary or tertiary color to material button

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by shhdharmen** [comment]
@alanpurple are you looking for https://material.angular.io/guide/theming#context-specific-themes?

```scss
[color=primary] {
  @include mat.theme((
    color: mat.$cyan-palette,
  ));
}
```

**Comment by alanpurple** [comment]
I think this is the only way

```
<button mat-button style="color:var(--mat-sys-error)">button</button>
```

**Comment by shhdharmen** [comment]
Using CSS directly may not be a good idea. You can follow any of the following approach:

1. Use `mat.theme` within a selector, like [here](https://material.angular.io/guide/theming#context-specific-themes)
2. Use `mat.theme-overrides` within a selector, like [here](https://material.angular.io/guide/system-variables#overrides)
3. Use `mat.button-overrides` within a selector, like [here](https://material.angular.io/components/button/styling)
4. There is also one another way of using component color variants, it's not documented in latest docs, but it was there in [v18 docs](https://v18.material.angular.io/guide/theming#using-component-color-variants).
5. If you really need to use CSS only, make sure to give colors for all the needed system variables. Buttons primarily rely on `primary` colors, you may want to override each of the following [system variables](https://material.angular.io/guide/system-variables):

```css
[color=error] {
  --mat-sys-primary: var(--mat-sys-error);
  --mat-sys-on-primary: var(--mat-sys-on-error);
}
```
