### ISSUE TITLE
Better readable SCSS variable names

### ISSUE THREAD

**Issue by SvenBudak** [angular/components#30377]
### Feature Description

I'm currently styling my Material components and find it incredibly time-consuming to keep track of everything.

```scss
:root { 
  @include mat.form-field-overrides(( 
    filled-label-text-color: #303030, 
    filled-hover-label-text-color: red, 
    filled-focus-label-text-color: blue,  
  )); 
}
```

It would be so much easier to read if the variables were named like this:
```scss
filled-label-text-color: #303030  
filled-label-text-color-hover: red  
filled-label-text-color-focus: blue  
```

I’m aware that even if this were considered "correct," it probably wouldn’t be changed retroactively since it would be a breaking change... but hope dies last.

**Comment by wagnermaciel** [comment]
Hi, @SvenBudak the token names are long out of necessity. We need to prefix them to differentiate our components from other libraries / projects / design systems. We also need to include the component in their name since different components might have tokens with the same name. For example, filled-label-text-color might be something that exists in form-field and the button.

The `overrides` mixins are meant to make the tokens easier to use by removing the need to remember those prefixes. The mixin also guarantees that the tokens you define exist and are not misspelled. If you tried using the variables directly and misspelled one, you would have no idea since the css would assume you were just defining a new variable.

**Comment by SvenBudak** [comment]
> Hi, [@SvenBudak](https://github.com/SvenBudak) the token names are long out of necessity. We need to prefix them to differentiate our components from other libraries / projects / design systems. We also need to include the component in their name since different components might have tokens with the same name. For example, filled-label-text-color might be something that exists in form-field and the button.
> 
> The `overrides` mixins are meant to make the tokens easier to use by removing the need to remember those prefixes. The mixin also guarantees that the tokens you define exist and are not misspelled. If you tried using the variables directly and misspelled one, you would have no idea since the css would assume you were just defining a new variable.

I'm not sure if you understood my request. I suggested keeping the full component name but writing it as one word and attaching the "state" as a suffix.  

As I mentioned in my opening post, right now you're basically splitting up the component name and inserting something like "hover" somewhere in the middle. In my opinion, that makes it really hard to read. You always have to take a few extra steps to figure out which variable you're actually working with.

**Comment by wagnermaciel** [comment]
The example you showed doesn't include the full component name. The css variables that get outputted from tokens look like this:

```
--mdc-filled-text-field-label-text-color
--mdc-outlined-text-field-label-text-color
--mat-select-enabled-trigger-text-color
```

Is the request that the tokens get renamed like this:


```scss
// Before
:root { 
  @include mat.form-field-overrides(( 
    filled-label-text-color: #303030, 
    filled-hover-label-text-color: red, 
    filled-focus-label-text-color: blue,  
  )); 
}

// After
:root { 
  @include mat.form-field-overrides((
    filled-label-text-color: #303030,
    filled-label-text-color-hover: red,
    filled-label-text-color-focus: blue,
  )); 
}
```

Or that the css variables get renamed?

```scss
// Before
--mdc-filled-text-field-label-text-color
--mdc-filled-hover-text-field-label-text-color
--mdc-filled-focus-text-field-label-text-color

// After
filled-label-text-color
filled-label-text-color-hover
filled-label-text-color-focus
```
