### ISSUE TITLE
bug(MatList): Icons do not respect RTL direction

### ISSUE THREAD

**Issue by withpouriya** [angular/components#30537]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using MatList in an RTL project, the icons do not adjust their margins correctly based on the text direction (dir="rtl"). The left and right margins remain the same as in LTR mode, causing misalignment in RTL layouts.

I was able to fix this issue easily with custom CSS, but I wanted to report it as a bug in case it needs to be addressed in the library.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Icons should switch their margins correctly when dir="rtl" is set.

### Actual Behavior

Icons remain aligned as if the project is LTR, leading to incorrect spacing.

### Environment

Angular: 18
Angular Material: 19.1.5
Browser: Latest version of Chrome
Operating System: Windows (running a Linux dev container on WSL)

**Comment by crisbeto** [comment]
This isn't enough information to investigate. Can you show what your markup looks like?

**Comment by withpouriya** [comment]
![Image](https://github.com/user-attachments/assets/09a50088-9024-49cf-a903-a885de8bf2e0)
Sure! As you can see in this image, the default padding of mat-icon in the list is more on the left side than on the right, whereas for RTL, it should be the opposite.

**Comment by orelby** [comment]
I see this issue in `matListItemIcon`. It seems that the added specificity of `[dir="rtl"]` causes the fixed physical RTL properties to override the logical properties variable declarations.

```css

[dir="rtl"] .mdc-list-item--with-leading-icon .mdc-list-item__start {
    margin-left: 32px;
    margin-right: 16px;
}

.mdc-list-item--with-leading-icon .mdc-list-item__start {
    margin-inline-start: var(--mat-list-list-item-leading-icon-start-space, 16px);
    margin-inline-end: var(--mat-list-list-item-leading-icon-end-space, 16px);
}

.mdc-list-item--with-leading-icon .mdc-list-item__start {
    // ...
    margin-left: 16px;
    margin-right: 32px;
}

```
