### ISSUE TITLE
feat(mat-form-field / mat-label): we need the option to NOT truncate, a long/multi-line mat-label within a mat-form-field

### ISSUE THREAD

**Issue by doublehelix** [angular/components#30578]
### Feature Description

We have a situation where we need a very short input (4 digits) but it has a very long label.
MUCH wider than the required input, and sometimes, much wider than the parent container/page.

Unfortunately, specifying a size on the mat-form-field not only resizes the input, it also resizes and truncates the label to the point of uselessness.

Examples:

In the first field below, we've set the `mat-form-field` style to `width: 16.666667%`

Small input with truncated label:
![Image](https://github.com/user-attachments/assets/f4f0700a-be3a-4983-90d6-7668ecc2fce7)

Updated styles with label width 600% to match the parent container (6 x 16.666667%)
This _does_ make the label the full width, however, it's still not big enough to display the full text:
```css
.mat-mdc-form-field .mat-mdc-text-field-wrapper .mat-mdc-form-field-flex .mat-mdc-form-field-infix .mat-mdc-floating-label {
    width: 600% !important;
}
```
![Image](https://github.com/user-attachments/assets/8c340ece-dbc6-48b8-91a0-d8b865bbae04)

So, we added wrapping, to ensure the full label (and the trailing tooltip icon component within the label) is displayed:
```css
.mat-mdc-form-field .mat-mdc-text-field-wrapper .mat-mdc-form-field-flex .mat-mdc-form-field-infix .mat-mdc-floating-label {
    width: 600% !important;
    text-wrap: auto;
}
```
Unfortunately, this then overlaps the input, as the position of the label is hard-coded in the material styles...

![Image](https://github.com/user-attachments/assets/4f86cbd5-f059-443d-849f-6c3f3132da89)

Given the DOM of the component after rendering, I can't see any simple way to untangle this problem.

Obviously, on mobile devices this problem is exacerbated substantially:

![Image](https://github.com/user-attachments/assets/71e24f13-2293-4010-9910-9fb56974cc80)

Any suggestions would be great.
