### ISSUE TITLE
bug(theming): [v20.0.1] brand-family not being set along plain-family when using a single font-family value for mat.theme typography (uses default Roboto)

### ISSUE THREAD

**Issue by anisabboud** [angular/components#31254]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19.2.17

### Description

If you define a `mat.theme` with a single value for typography, the font is not applying to some headings such as dialog-title. They are using the default Roboto font.

I believe the bug is in line 117 in [_m3-system.scss](https://github.com/angular/components/blob/020c6afd8b8d7e2d830c7a563f2f06fae09dfa9a/src/material/core/tokens/_m3-system.scss#L117).
If `$typography` is not a map (`@else` clause), then only `$plain: $typography;` is being set, while `$brand` remains `$plain;` from line 106, which is `(Roboto, sans-serif)` (from line 105).

https://github.com/angular/components/blob/020c6afd8b8d7e2d830c7a563f2f06fae09dfa9a/src/material/core/tokens/_m3-system.scss#L104-L118

### Reproduction

Steps to reproduce: Define a `mat.theme` with a single value for `typography`:
```scss
html {
  color-scheme: light;
  @include mat.theme((
    color: $primary-palette,
    typography: $my-font,  // Should apply to both `plain-family` and `brand-family`, but it's not applying to `brand-family`.
    density: 0,
  ));
}
```

### Expected Behavior

https://material.angular.dev/guide/theming#single-font-family-value
> If you provide a font family, Angular Material uses it for all the text in its components.

![Image](https://github.com/user-attachments/assets/515a92e1-9719-4564-926a-fe289eb2480f)

### Actual Behavior

The single provided font-family is being applied to all components, but not to some headers like dialog-title, 

### Environment

- Angular: `20.0.0`
- CDK/Material: `20.0.1`
- Browser(s): `Chrome`
