### ISSUE TITLE
<mat-dialog-actions>: Button spacing does not match MD spec

### ISSUE THREAD

**Issue by jnamesky** [angular/components#3528]
#### Bug, feature request, or proposal:
Buttons that are inside `mat-dialog-actions` currently have no padding/margin to the left or right. There should be padding between buttons as described in the Material Design spec.
Buttons  inside `mat-card-actions` do have a margin left and right of 4px, providing some sort of spacing.

#### What is the expected behavior?
See Material Design dialogs specs:
[https://material.io/guidelines/components/dialogs.html#dialogs-specs](url)

#### What is the current behavior?
See screenshot below taken from the Angular Material example site.

![codeexample-md-dialog-mdbuttons](https://cloud.githubusercontent.com/assets/25941692/23738037/b142a002-04ea-11e7-9072-4f924ae0c2b2.png))

#### What are the steps to reproduce?

Visit the Angular Material example site:
[https://material.angular.io/components/component/dialog](url)

#### What is the use-case or motivation for changing an existing behavior?
Match Material Design spec.

**Comment by Kyderman** [comment]
As an extension, would it not be possible to get some sort of button-group class?

Im finding that buttons pretty much anywhere have incorrect spacing.

A button group class that applies the correct padding horizontally and then vertically in smaller screen sizes would be very useful, and due to it being part of the spec, should be provided in the scope of this library.

**Comment by jnamesky** [comment]
The button-group class is a good idea - and it would be great to have the ability to vertically stack these button groups on smaller screens (or whatever size you'd require).

**Comment by jnamesky** [comment]
For now we're just using a modification of the `md-card-actions` button styling.

```
.mat-dialog-actions .mat-button:first-child, .mat-dialog-actions .mat-raised-button:first-child {
    margin-left: 0;}
.mat-dialog-actions .mat-button:last-child, .mat-dialog-actions .mat-raised-button:last-child {
    margin-right: 0;}
.mat-dialog-actions .mat-button, .mat-dialog-actions .mat-raised-button {
    margin: 0 4px;}
```

**Comment by arlowhite** [comment]
This is what I do in my SCSS:

```scss
.mat-dialog-actions {
  // align buttons to right as shown in Material Design guide
  justify-content: flex-end;

.mat-button {
  &:not(:first-child) {
      margin-left: 1em;
    }
  }
}

.flex-spacer {
  flex: 1 1 auto;
}
```

If I want to push a button to the left side, I put a greedy span in-between the buttons.
```html
<span class="flex-spacer"></span>
```

But if you want to support RTL layouts, that's a whole other issue.

**Comment by demetrio812** [comment]
Hello,
I'd like to contribute to this by adding another problem with alignment: when I right align the actions in my dialog by using `<md-dialog-actions align="end">` it still doesn't follow the guidelines in terms of spacing:

These 2 are from the guidelines:

<img width="376" alt="screenshot 2017-07-07 12 46 37" src="https://user-images.githubusercontent.com/385644/27957009-43c9504c-6314-11e7-853d-640980c38743.png">

<img width="325" alt="screenshot 2017-07-07 12 46 53" src="https://user-images.githubusercontent.com/385644/27957013-483c4eae-6314-11e7-86c4-e2982c739d14.png">

And this is generated by this simple code:

```
<h2 md-dialog-title *ngIf="data.title">{{data.title}}</h2>
<md-dialog-content>{{data.message}}</md-dialog-content>
<md-dialog-actions align="end">
  <button md-button md-dialog-close>Close</button>
</md-dialog-actions>
```

This is the result: 

<img width="308" alt="screenshot 2017-07-07 12 46 02" src="https://user-images.githubusercontent.com/385644/27957030-5307aad6-6314-11e7-96aa-734394358b2b.png">

<img width="307" alt="screenshot 2017-07-07 12 46 09" src="https://user-images.githubusercontent.com/385644/27957033-56ced3b0-6314-11e7-8272-12c4b9adf56b.png">

You can see that there is an extra space there, is it a bug or am I supposed to use something else instead of md-buttons?

**Comment by Splaktar** [comment]
@demetrio812 yep, I'm seeing that as well. It's due to this CSS:

```
.mat-dialog-container {
  padding: 24px;
}
```

It seems to make it impossible to align the action buttons with the spacing defined in the Material Design spec.

**Comment by Splaktar** [comment]
@demetrio812 I was able to work around this using the `panelClass` API of md-dialog, setting my dialog's `ViewEncapsulation.NONE`, and applying the following styles to my class:

```
this.dialog.open(CustomDialogComponent, {panelClass: 'customDialog'})
```

```
.customDialog {
  .mat-dialog-container {
    padding: 24px 0 0;

    [md-dialog-title],
    md-dialog-content {
      padding: 0 24px;
    }
    hfc-confirmation-dialog {
      display: flex;
      flex-direction: column;
    }
    md-dialog-actions {
      padding: 8px;

      .mat-button {
        padding: 0 8px;
        min-width: 64px;

        &:nth-child(even) {
          margin-left: 8px;
        }
      }
    }
  }
}
```

These seemed to have the best match with the Material Design spec.

**Comment by Splaktar** [comment]
I had to put together some new styles for the latest stable builds:
```scss
. customDialog {
  .mat-dialog-container {
    padding: 24px 0 24px 0;

    [mat-dialog-title] {
      margin: 0 24px 24px;
    }
    .mat-dialog-content {
      margin: 0;
    }
    app-custom-dialog {
      display: flex;
      flex-direction: column;
    }
    .mat-dialog-actions {
      padding: 8px;

      .mat-button {
        padding: 0 8px;
        min-width: 64px;

        &:nth-child(even) {
          margin-left: 8px;
        }
      }
    }
  }
```
