### ISSUE TITLE
[Tabs] Provide an alignTabs property

### ISSUE THREAD

**Issue by ddyrcz** [angular/components#4100]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?

Regarding to design doc there should be property [alignTabs]

![image](https://cloud.githubusercontent.com/assets/20314986/25054889/e516a2e8-215f-11e7-8f31-9e4febe1ccb8.png)

Doc:
https://docs.google.com/document/d/1djxF6AKGijZl6LOoJ0asFbkf1-GqSAp1CSIyurtKVog/preview#

#### What is the current behavior?

There is no such a property

#### What is the use-case or motivation for changing an existing behavior?

I have to center the labels align

Instead of this:

![image](https://cloud.githubusercontent.com/assets/20314986/25055025/c0592038-2160-11e7-8a72-008348d76242.png)

I would like to aligh them like this:

![image](https://cloud.githubusercontent.com/assets/20314986/25055139/67f759fe-2161-11e7-9924-4b3b896dfc18.png)

**Comment by cpboyd** [comment]
From my perspective, it wouldn't be quite as bad if you could simply use @angular/flex-layout on the elements...
e.g.:
```html
  <nav mat-tab-nav-bar fxLayout="row" fxLayoutAlign="space-around center">
    ...
  </nav>
```

Except that with the `mat-tab-nav-bar` directive, it creates an internal `<div>` to register `cdkObserveContent`.

A work-around requires use of `::ng-deep` in the style:
```SCSS
.mat-tab-nav-bar {
  ::ng-deep .mat-tab-links {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-around;
  }
}
```
