### ISSUE TITLE
(feature) expansion panel: secondary content & description alignment

### ISSUE THREAD

**Issue by mattheiler** [angular/components#5173]
#### Bug, feature request, or proposal:
Feature.

#### What is the expected behavior?
Secondary content is supported by expansion panel header.
The descriptions should line up.
[GUIDELINES](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage)

#### What is the current behavior?
Expansion panel has a fixed height and line height. Secondary content is not supported.
The descriptions don't line up.

#### What are the steps to reproduce?
[ROUGH EXAMPLE](http://plnkr.co/edit/o4tPe0foN87adpykIqMQ?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
Support secondary content.
Align descriptions in a column.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 2.0.0-beta.6-*

**Comment by julianobrasil** [comment]
Maybe adding **`flex-basis: 0`** to **`mat-expansion-panel-header-title`** and **`mat-expansion-panel-header-description`** could fix the alignment.

**Comment by mattheiler** [comment]
Using flex layout and assigning fxFlex="50%" to the title fixes the alignment issue. However, still cant display secondary content, as of beta 8.

**Comment by dmitrysteblyuk** [comment]
Does anybody managed to come up with a workaround?
I guess the problem here is with expansionHeight trigger for MdExpansionPanelHeader, which sets fixed line-height and height styles. I tried to override them using css !important flag and was quite surprised to find out it doesn't work during animation.

**Comment by julianobrasil** [comment]
@dmitrysteblyuk, if you're using an **<md-accordion>** try this:

```html
<md-accordion class="my-headers-align">
```

in the component css class:

```css
.my-headers-align .mat-expansion-panel-header-title, 
.my-headers-align .mat-expansion-panel-header-description {
  flex-basis: 0;
}
```

If you're using just the **<md-expansion-panel>**, use `my-headers-align` class directly in it. 

Or, to set it globally, just ommit the .my-headers-align part in styles.css:

```css
.mat-expansion-panel-header-title, 
.mat-expansion-panel-header-description {
  flex-basis: 0;
}
```
