### ISSUE TITLE
Allow overriding of theme background and foreground colors

### ISSUE THREAD

**Issue by mackelito** [angular/components#6244]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
Add documentation on how to set background in a custom theme to https://material.angular.io/guide/theming

#### What is the current behavior?
No docs

#### What are the steps to reproduce?
https://material.angular.io/guide/theming

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### What is the use-case or motivation for changing an existing behavior?
Makes it easier to customise themes

**Comment by literalpie** [comment]
Should developers be encouraged to set background colors of a theme? Or do we just want documentation on using the background color from a theme? 

put differently:
Do we want to (a) show people how to change the value of `map-get($theme, background)`, or do we want to (b) document that `map-get($theme, background)` can be used?

**Comment by fabienbranchel** [comment]
@literalpie : I'd like to know how to set background colors of a theme when I create it.

**Comment by literalpie** [comment]
@fabienbranchel 
If you want to set the background colors, you likely want to customize the entire background and foreground palette by emulating the [mat-light-theme](https://github.com/angular/material2/blob/3352201eabcf66c23e6c2297b800828003eaf0fc/src/lib/core/theming/_theming.scss#L62) or mat-dark-theme functions with your own replacement. Your replacement would include your own palettes instead of the [mat-light-theme-foreground](https://github.com/angular/material2/blob/48ff4ba74a92924dc42ae2fd1592351c630fbb1b/src/lib/core/theming/_palette.scss#L704) and background palettes.

example: https://stackblitz.com/edit/angular-material-custom-background?file=theme.scss

**Comment by intellix** [comment]
Would be nice if those 2 functions were similar to how red has defaults to allow overriding without copy/pasting:

```scss
// Creates a container object for a light theme to be given to individual component theme mixins.
@function mat-light-theme($primary, $accent, $warn: mat-palette($mat-red), $foreground: mat-palette($mat-light-theme-foreground), $background: mat-palette($mat-light-theme-background)) {
  @return (
    primary: $primary,
    accent: $accent,
    warn: $warn,
    is-dark: false,
    foreground: $foreground,
    background: $background,
  );
}

// Creates a container object for a dark theme to be given to individual component theme mixins.
@function mat-dark-theme($primary, $accent, $warn: mat-palette($mat-red), $foreground: mat-palette($mat-dark-theme-foreground), $background: mat-palette($mat-dark-theme-background)) {
  @return (
    primary: $primary,
    accent: $accent,
    warn: $warn,
    is-dark: true,
    foreground: $foreground,
    background: $background,
  );
}
```

**Comment by ktsangop** [comment]
I have also struggled to find a way to set the app background, and unfortunately the proposed solutions do not work if the app is not wrapped in a material component.

For example, in @literalpie 's example, the app is wrapped inside a `mat-sidenav-container` component.

The only way i have found to set the background for `app-root`, is to inculde the following in your `styles.scss` file (or whatever the name of the file that you declare on your `angular.json` definition)

```
app-root {
  background: map-get($mat-dark-theme-background, background );
}
```
That will work, provided that you have declared the `$mat-dark-theme-background` map, and it is helpful because you keep your background color declared in one place (`theme.scss`). 

Of course you can any color there that is independent of the theme you have created, but this might be harder to maintain.

**Comment by literalpie** [comment]
@ktsangop I think you're missing this: 

> Finally, if your app's content is not placed inside of a mat-sidenav-container element, you need to add the mat-app-background class to your wrapper element (for example the body). This ensures that the proper theme background is applied to your page.

[source](https://material.angular.io/guide/theming)

**Comment by literalpie** [comment]
> To be honest whilst reading into all of the helpers the `mat-light-theme()` and `mat-dark-theme()` functions add an extra layer of complexity that doesn't add anything IMO

Are you saying that instead of having the two functions, someone would use the dark theme by passing the foreground and background? I could get on board with that.

**Comment by ktsangop** [comment]
> @ktsangop I think you're missing this:
> 
> > Finally, if your app's content is not placed inside of a mat-sidenav-container element, you need to add the mat-app-background class to your wrapper element (for example the body). This ensures that the proper theme background is applied to your page.
> 
> [source](https://material.angular.io/guide/theming)

🤦‍♂  OK, i have totally missed that! 🤣 

FWIW, my solution, applies the background color event before the app.component is bootstraped, which in my case makes a custom loading spinner i have, being displayed using the theme background color.

Instead, adding the `mat-app-background` class to the `<body>` does not have the same effect.

**Comment by prabhat22** [comment]
i am trying to use angular material with a theme built in scss,angular,bootstrap , i  have install it using npm and add all the neccessary files, also it is not showing any error yet i am not able to use it components

**Comment by the-blackpirate** [comment]
Just add Material theming in your angular project.

> ng add @angular/material

then choose custom theming option and paste the below code you will get black dark theming and if you wanna customize material color scheme then go to https://material.io and go material color palette and select your custom color scheme for your navbar and button(other components).

> @import "~@angular/material/theming";
> 
> $custom-typography: mat-typography-config(
>   $font-family:
>     "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif"
> );
> 
> @include mat-core($custom-typography);
> 
> $your-app-name-primary: mat-palette($mat-purple, 200);
> $your-app-name-accent: mat-palette($mat-teal, 200);
> $your-app-name-warn: mat-palette($mat-red);
> $your-app-name-theme: **mat-dark-theme**(
>   $your-app-name-primary,
>   $your-app-name-accent,
>   $your-app-name-warn
> );
> 
> @include angular-material-theme($your-app-name-theme);

**Comment by nair-ayush** [comment]
Just found this thread. I've been trying to figure out themes for a long time. Couldn't find a concrete solution until now. Making it work by adding `<mat-sidenav-container>` over the app. So thank you @literalpie . But can you give an example of how to add the `mat-app-background` to the _body_ element?

However, if I don't have enough content on the window then the rest of the background remains white(default color) only. So you would need to modify the style of `<mat-sidenav-container>`  to max out it's height. You can see the `app.component.css` to look at what I've done.

I have applied the theme toggle in my header and as per Angular Material docs, added an extra class to the `div` wrapper by adding an _id_ and modifying it's style in `theme.service.ts`. 

**custom_theme.scss**
```scss
@import "~@angular/material/theming";
@include mat-core();

// LIGHT THEME

$light-primary: mat-palette($mat-indigo);
$light-accent: mat-palette($mat-yellow, A200, A100, A400);
$light-warn: mat-palette($mat-red);
$light-theme: mat-light-theme($light-primary, $light-accent, $light-warn);
@include angular-material-theme($light-theme);

// DARK THEME

$dark-primary: mat-palette($mat-grey);
$dark-accent: mat-palette($mat-amber, A200, A100, A400);
$dark-warn: mat-palette($mat-red);
// Create the theme object (a Sass map containing all of the palettes).
$dark-theme: mat-dark-theme($dark-primary, $dark-accent, $dark-warn);

.dark-theme {
  @include angular-material-theme($dark-theme);
}
```
**app.component.html**
```html
<div id="alternative-theme">
  <mat-sidenav-container class="app-container">
    <app-header></app-header>
    <router-outlet> </router-outlet>
    <app-footer></app-footer>
  </mat-sidenav-container>
</div>
```
**app.component.css**
``` css
#alternative-theme {
  display: block;
  height: 100%;
}

.app-container {
  height: inherit;
}
```
**theme.service.ts**
``` typescript
import { Injectable } from "@angular/core";
import { OverlayContainer } from "@angular/cdk/overlay";

@Injectable({
  providedIn: "root"
})
export class ThemeService {
  constructor(private overlayContainer: OverlayContainer) {
    this.overlayContainer = overlayContainer;
  }

  setDarkTheme() {
    document.getElementById("alternative-theme").classList.add("dark-theme");
    document.getElementById("footer-text").classList.remove("dark");
    this.overlayContainer.getContainerElement().classList.add("dark-theme");
  }

  setLightTheme() {
    document.getElementById("alternative-theme").classList.remove("dark-theme");
    document.getElementById("footer-text").classList.add("dark");
    this.overlayContainer.getContainerElement().classList.remove("dark-theme");
    document;
  }
}
```

_Is this the best way to toggle between themes or is there a more robust way?_ I'm just starting with Angular and Material UI and if you have anything to add to the above snippets to make it better will be appreciated. Cheers.

**Comment by the-ult** [comment]
@nair-ayush 

Just put the classes on your body or app:

```html
<body class="mat-typography mat-app-background">
    <app-root></app-root>
  </body>
```

@see https://material.angular.io/guide/theming#using-a-pre-built-theme

> Finally, if your app's content is not placed inside of a mat-sidenav-container element, you need to add the mat-app-background class to your wrapper element (for example the body). This ensures that the proper theme background is applied to your page.

**Comment by tomasdev** [comment]
Adding onto @intellix proposal:

It'd be backwards compatible to change the current `mat-light-theme` (and `mat-dark-theme` with the proper methods) implementations to call:

```
@function mat-light-theme(...) {
  // ...
  $result: $primary;
  @if map_get($primary, color) {
    $color-settings: map_get($primary, color);
    $primary: map_get($color-settings, primary);
    $accent: map_get($color-settings, accent);
    $warn: map_get($color-settings, warn);
    $foreground: map_get($color-settings, foreground);
    $background: map_get($color-settings, background);
    $result: map_merge($result, (color: _mat-create-light-color-config($primary, $accent, $warn, $foreground, $background)));
  }
  @return _mat-create-backwards-compatibility-theme(_mat-validate-theme($result));
}
```

And then have
```
@function _mat-create-light-color-config($primary, $accent, $warn: null, $foreground: $mat-light-theme-foreground, $background: $mat-light-theme-background) {
  @return (
    primary: $primary,
    accent: $accent,
    warn: if($warn != null, $warn, mat-palette($mat-red)),
    is-dark: false,
    foreground: $foreground,
    background: $background,
  );
}
```

This way, guarantees that people using the older stuff still works (since it defaults to the global variables) and yet people who want can use the cleaner method:
```
$theme: mat-light-theme((
  color: (
    primary: $primary,
    accent: $accent,
    warn: $warn,
    background: (
    app-bar: #fff,
    ),
  ),
));
```

**Comment by diosney** [comment]
Hopefully this gets added soon.

It is pretty annoying to being able to set primary, accent and warn palettes, and not being able to set the foreground and background ones in an easy way.

**Comment by anschm** [comment]
Can this please added soon. Thx.

**Comment by rscircus** [comment]
This took me days to find this issue from 2017... phew.

**Comment by rscircus** [comment]
OK, I managed to also apply the light/dark toggling to the whole app by putting everything in a container of class 'mat-app-background'.

**Comment by rscircus** [comment]
Like so:

![image](https://user-images.githubusercontent.com/1167114/124997677-5c431000-e04b-11eb-8271-894b72367d9a.png)

**Comment by noumnoum** [comment]
Hi guys,

This work for me :

```
@use '~@angular/material' as mat;
@include mat.core();

$dark-theme-background-palette: (
  status-bar: red,
  app-bar: red,
  background: red,
  hover: red,
  card: red,
  dialog: red,
  disabled-button: red,
  raised-button: red,
  focused-button: red,
  selected-button: red,
  selected-disabled-button: red,
  disabled-button-toggle: red,
  unselected-chip: red,
  disabled-list-option: red,
  tooltip: red
);

mat.$dark-theme-background-palette: $dark-theme-background-palette;
```

-  "@angular/core": "~12.1.2"
- "@angular/material": "^12.1.4"

tchuss ;)

**Comment by Neutrino-Sunset** [comment]
Where is it even documented what the sass identifiers for the background and foreground colours are? I don't even want to cutomize these values, I'm just trying to work out how to apply the existing theme values of the neutral colors plus lighter and darker variants to a custom component, but the documentation on using a theme in a custom component has no information on this at all.

https://material.angular.io/guide/theming-your-components

**Comment by michaelfaith** [comment]
> Where is it even documented what the sass identifiers for the background and foreground colours are? I don't even want to customize these values, I'm just trying to work out how to apply the existing theme values of the neutral colors (plus lighter and darker variants) to a custom component, but the documentation on using a theme in a custom component has no information on this at all.
> 
> https://material.angular.io/guide/theming-your-components

It isn't documented at all, as far as i know. I just had to dig through the code to figure it out: https://github.com/angular/components/blob/c649f7dfca3df2cd3a47365a2930718dab4a8a09/src/material/core/theming/_palette.scss#L694

**Comment by Neutrino-Sunset** [comment]
So is using these hardcoded variable names officially supported, or is that something that's likely to break in a future release?

**Comment by mattiLeBlanc** [comment]
I just want to change the 'text' colour from the 'foreground' map. You used to be able to do it like described here: https://newbedev.com/how-to-change-font-color-of-primary-palette-in-angular-material2
but now that is no longer possible.

Why can't we support something like:

```
$core-theme: mat.define-light-theme((
  color: (
    primary: $primary,
    accent: $accent,
    warn: $warn,
    foreground: (
      base:              black,
      divider:           $dark-dividers,
      dividers:          $dark-dividers,
      disabled:          $dark-disabled-text,
      disabled-button:   rgba(black, 0.26),
      disabled-text:     $dark-disabled-text,
      elevation:         black,
      hint-text:         $dark-disabled-text,
      secondary-text:    $dark-secondary-text,
      icon:              rgba(black, 0.54),
      icons:             rgba(black, 0.54),
      text:              red,
      // text:              rgba(black, 0.87),
      slider-min:        rgba(black, 0.87),
      slider-off:        rgba(black, 0.26),
      slider-off-active: rgba(black, 0.38),
    )
  )
));
```
so I can change the text colour to whatever I want.
And yes, the main issue is the mat-drawer-container getting the colour from foreground.text.
I don't really want to CSS hack it is I can do it in a nice way.

**Comment by michaelfaith** [comment]
> I just want to change the 'text' colour from the 'foreground' map. You used to be able to do it like described here: https://newbedev.com/how-to-change-font-color-of-primary-palette-in-angular-material2 but now that is no longer possible.
> 
> Why can't we support something like:
> 
> ```
> $core-theme: mat.define-light-theme((
>   color: (
>     primary: $primary,
>     accent: $accent,
>     warn: $warn,
>     foreground: (
>       base:              black,
>       divider:           $dark-dividers,
>       dividers:          $dark-dividers,
>       disabled:          $dark-disabled-text,
>       disabled-button:   rgba(black, 0.26),
>       disabled-text:     $dark-disabled-text,
>       elevation:         black,
>       hint-text:         $dark-disabled-text,
>       secondary-text:    $dark-secondary-text,
>       icon:              rgba(black, 0.54),
>       icons:             rgba(black, 0.54),
>       text:              red,
>       // text:              rgba(black, 0.87),
>       slider-min:        rgba(black, 0.87),
>       slider-off:        rgba(black, 0.26),
>       slider-off-active: rgba(black, 0.38),
>     )
>   )
> ));
> ```
> 
> so I can change the text colour to whatever I want. And yes, the main issue is the mat-drawer-container getting the colour from foreground.text. I don't really want to CSS hack it is I can do it in a nice way.

Yep, passing in the foreground and background overrides, and the define-*-theme function merging those onto the default would be my preference too.  The only way I've been able to do it, is use the define function to generate the theme object, and then override those props on after the fact. It's hacky, and would much prefer a way to do it that's officially supported, but it works for now.

**Comment by michaelfaith** [comment]
This function (and the dark theme version) is what would likely need to change, to allow for those parameters, instead of only taking defaults.

https://github.com/angular/components/blob/c649f7dfca3df2cd3a47365a2930718dab4a8a09/src/material/core/theming/_theming.scss#L114-L123

**Comment by lerabela** [comment]
Until a fix is added. just bypass the create theme function in your main style file. 

see solution:  [https://stackblitz.com/edit/angular-material-custom-background?file=theme.scss](https://stackblitz.com/edit/angular-material-custom-background?file=theme.scss)

**Comment by dgutoryan** [comment]
Don't work:
```
$custom-theme: mat.define-light-theme(
  (
    color: (
      primary: $custom-primary,
      accent: $custom-accent,
      warn: $custom-warn,
    ),
  )
);

$background: (
  app-bar: red,
  background: #ffffff,
);

$custom-theme: map-merge(
  $custom-theme,
  (
    background: $background,
  )
);
```

It would be nice to have easy way to change background and foreground

**Comment by MikaStark** [comment]
I agree that providing a way to easily customizing foreground and background colors would be a blast.
Until now, I use my own theme mixin that override the existing one (in order to stay compatible with Material). But I would prefer Material provide the way to do it properly by passing just foreground and background variables (just like the other colors)
Anyway, if someone is interesting in my code, here it is :

*src/app/core/theming/_palette.scss*
```scss
@use "sass:map";

// Of course you can customize everything ;)

$dark-primary-text: rgba(#000939, 0.87);
$dark-secondary-text: rgba(#000939, 0.54);
$dark-disabled-text: rgba(#000939, 0.38);
$dark-dividers: rgba(#000939, 0.12);
$dark-focused: rgba(#000939, 0.12);
$light-primary-text: white;
$light-secondary-text: rgba(white, 0.7);
$light-disabled-text: rgba(white, 0.5);
$light-dividers: rgba(white, 0.12);
$light-focused: rgba(white, 0.12);

$grey-palette: (
  50: #f7f9ff,
  100: #f1f3fb,
  200: #e8eaf2,
  300: #d9dbe3,
  400: #b5b7bf,
  500: #96979f,
  600: #6d6f76,
  700: #5a5b62,
  800: #3b3d43,
  900: #1b1c22,
  contrast: (
    50: $dark-primary-text,
    100: $dark-primary-text,
    200: $dark-primary-text,
    300: $dark-primary-text,
    400: $dark-primary-text,
    500: $dark-primary-text,
    600: $light-primary-text,
    700: $light-primary-text,
    800: $light-primary-text,
    900: $light-primary-text,
  ),
);

$night-palette: (
  50: #e3ecff,
  100: #bed1e9,
  200: #9eb1ce,
  300: #7c92b2,
  400: #637c9e,
  500: #4a668b,
  600: #3c597a,
  700: #2d4664,
  800: #1e344e,
  900: #0b2137,
  contrast: (
    50: $dark-primary-text,
    100: $dark-primary-text,
    200: $dark-primary-text,
    300: $light-primary-text,
    400: $light-primary-text,
    500: $light-primary-text,
    600: $light-primary-text,
    700: $light-primary-text,
    800: $light-primary-text,
    900: $light-primary-text,
  ),
);

// Background palette for light themes.
$light-theme-background-palette: (
  status-bar: map.get($grey-palette, 300),
  app-bar: white,
  background: map.get($grey-palette, 50),
  hover: rgba(#243b53, 0.04),
  card: white,
  dialog: white,
  disabled-button: rgba(#243b53, 0.12),
  raised-button: white,
  focused-button: $dark-focused,
  selected-button: map.get($grey-palette, 300),
  selected-disabled-button: map.get($grey-palette, 400),
  disabled-button-toggle: map.get($grey-palette, 200),
  unselected-chip: map.get($grey-palette, 200),
  disabled-list-option: map.get($grey-palette, 200),
  tooltip: map.get($grey-palette, 700),
);

// Background palette for dark themes.
$dark-theme-background-palette: (
  status-bar: #0b2844,
  app-bar: map.get($night-palette, 900),
  background: #102a43,
  hover: rgba(white, 0.04),
  card: map.get($night-palette, 800),
  dialog: map.get($night-palette, 800),
  disabled-button: rgba(white, 0.12),
  raised-button: map.get($night-palette, 800),
  focused-button: $light-focused,
  selected-button: map.get($night-palette, 900),
  selected-disabled-button: map.get($night-palette, 800),
  disabled-button-toggle: #243b53,
  unselected-chip: map.get($night-palette, 700),
  disabled-list-option: #243b53,
  tooltip: map.get($night-palette, 700),
);

// Foreground palette for light themes.
$light-theme-foreground-palette: (
  base: #243b53,
  divider: $dark-dividers,
  dividers: $dark-dividers,
  disabled: $dark-disabled-text,
  disabled-button: rgba(#243b53, 0.26),
  disabled-text: $dark-disabled-text,
  elevation: #243b53,
  hint-text: $dark-disabled-text,
  secondary-text: $dark-secondary-text,
  icon: rgba(#243b53, 0.54),
  icons: rgba(#243b53, 0.54),
  text: rgba(#243b53, 0.87),
  slider-min: rgba(#243b53, 0.87),
  slider-off: rgba(#243b53, 0.26),
  slider-off-active: rgba(#243b53, 0.38),
);

// Foreground palette for dark themes.
$dark-theme-foreground-palette: (
  base: white,
  divider: $light-dividers,
  dividers: $light-dividers,
  disabled: $light-disabled-text,
  disabled-button: rgba(white, 0.3),
  disabled-text: $light-disabled-text,
  elevation: black,
  hint-text: $light-disabled-text,
  secondary-text: $light-secondary-text,
  icon: white,
  icons: white,
  text: white,
  slider-min: white,
  slider-off: rgba(white, 0.3),
  slider-off-active: rgba(white, 0.3),
);
```

*src/app/core/theming/_theming.scss*
```scss
@use '@angular/material' as mat;
@use 'sass:map';
@use 'palette';

@function define-light-theme($config) {
  $theme: mat.define-light-theme($config);
  $color: map.get($theme, color);
  $color: map.merge(
    $color,
    (
      background: palette.$light-theme-background-palette,
      foreground: palette.$light-theme-foreground-palette,
    )
  );
  @return map.merge(
    $theme,
    (
      color: $color,
    )
  );
}

@function define-dark-theme($config) {
  $theme: mat.define-dark-theme($config);
  $color: map.get($theme, color);
  $color: map.merge(
    $color,
    (
      background: palette.$dark-theme-background-palette,
      foreground: palette.$dark-theme-foreground-palette,
    )
  );
  @return map.merge(
    $theme,
    (
      color: $color,
    )
  );
}
```

*core/theming/_index.scss*
```scss
@forward "palette";
@forward "theming";

// Here you can forward your own themes located in core/themeing/themes
// @forward "themes/xxxx" as xxxx-*;
// ...
```

*src/styles.scss*
```scss
@use "@angular/material" as mat;
@use "app/core/theming" as app;
@use "sass:map";

@include mat.core();

$app-primary: mat.define-palette(mat.$indigo-palette);
$app-accent: mat.define-palette(mat.$pink-palette);

// Use your own "app" define-light-theme function instead of "mat" one.
$glx-theme: app.define-light-theme(
  (
    color: (
      primary: $app-primary,
      accent: $app-accent,
    )
  )
);
```
