### ISSUE TITLE
[Table] IE row height behaving differently

### ISSUE THREAD

**Issue by prabhat112** [angular/components#7496]
#### Bug, feature request, or proposal:
I have a basic md-table/cdk table where I am trying to change the row height. I have the below css code
```scss
.mat-table {
display: table;
width: 100%;
overflow: auto;
}  
.mat-header-row, .mat-row {
display: table-row;
padding: 0;
 border: none;
    }
.mat-header-cell,  .mat-cell {
display: table-cell;
**height: 24px;**
vertical-align: middle;
border-bottom: 1px solid rgba(0, 0, 0, 0.12);
font-size: 16px;
text-align: left;
}
```
or you can try the below link in both chrome and IE11

https://plnkr.co/edit/zFkOb41JwLUWetslAw1j?p=preview

#### What is the expected behavior?
IE11 should take the height of mat-cell as 24px or whatever is shown in the css file, but its defaulting to 48px. Chrome shows the correct behaviour.

#### What is the current behavior?
IE11 is defaulting to 48px.

#### What are the steps to reproduce?
https://plnkr.co/edit/zFkOb41JwLUWetslAw1j?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Trying to increase number of rows visible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

material 2.0.0.beta.11, angular 4.4.4, IE11 is affected
